---
# some basic variables
me:
  username: gbrown
  uid: 1000
  home: /home/gbrown
  name: 'Glenn Brown'

main_username: gbrown
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# grog.package
package_list:
  - name: apt-file
    yum_ignore: yes
    dnf_ignore: yes
  - name: aptitude
    yum_ignore: yes
    dnf_ignore: yes
  - name: bash-completion
  - name: bc
  - name: command-not-found
    yum: PackageKit-command-not-found
    dnf: PackageKit-command-not-found
  - name: curl
  - name: dialog
  - name: bind9-dnsutils
    yum: bind-utils
    dnf: bind-utils
  - name: epel-release
    apt_ignore: yes
  - name: git
  - name: gnupg2
  - name: gawk
  - name: htop
  - name: iotop
  - name: iftop
  - name: inxi
  - name: jq
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: openssh-server
  - name: python3
  - name: python3-apt
    yum_ignore: yes
    dnf_ignore: yes
  - name: python3-pip
  - name: python3-setuptools
  - name: pv
  - name: tmux
  - name: wget
  - name: screen
  - name: sudo
  - name: tree 
  - name: unzip
  - name: p7zip-full
    yum: p7zip
    dnf: p7zip
  - name: p7zip-rar
    yum: p7zip-plugins
    dnf: p7zip-plugins
  - name: vim
    yum: vim-enhanced
    dnf: vim-enhanced
  - name: zip

# bash_aliases
bash_aliases:
  - alias: "bashreload"
    command: "source ~/.bashrc && echo Bash config reloaded;"
  - alias: "dir"
    command: "ls --color=auto --format=vertical"
  - alias: "egrep"
    command: "egrep --color=auto"
  - alias: "fgrep"
    command: "fgrep --color=auto"
  - alias: "grep"
    command: "grep --color=auto"
  - alias: "l"
    command: "ls -CF --color=auto"
  - alias: "la"
    command: "ls -A --color=auto"
  - alias: "ll"
    command: "ls -l --color=auto"
  - alias: "vdir"
    command: "ls --color=auto --format=long"
  - alias: "mc"
    command: "/usr/share/mc/bin/mc-wrapper.sh"

bash_apt_aliases:
  - alias: agi
    command: "sudo apt install "
  - alias: agr
    command: "sudo apt remove "
  - alias: agu
    command: "sudo apt update && sudo apt upgrade"

bash_docker_aliases:
  - alias: "dtail"
    command: "docker logs -tf --tail='50' "
  - alias: "dstop"
    command: "docker stop `docker ps -aq`"
  - alias: "drm"
    command: "docker rm `docker ps -aq`"
  - alias: "dcp"
    command: "docker compose -f ~/docker-compose.yml "
  - alias: "dcporph"
    command: "docker compose -f ~/docker-compose.yml --remove-orphans "
  - alias: "dprune"
    command: "docker image prune"
  - alias: "dprunesys"
    command: "docker system prune --all"
  
bash_systemctl_aliases:
  - alias: sc-start
    command: "sudo systemctl start "
  - alias: sc-stop
    command: "sudo systemctl stop "
  - alias: sc-restart
    command: "sudo systemctl restart "
  - alias: sc-enable
    command: "sudo systemctl enable "
  - alias: sc-disable
    command: "sudo systemctl disable "
  - alias: sc-status
    command: "sudo systemctl status "
  - alias: sc-reload
    command: "sudo systemctl daemon-reload"


# geerlingguy.ntp
ntp_timezone: America/New_York

# grog.package
package_update_cache: true

# grog.authorized-key
authorized_key_list:
  - name: "{{ main_username }}"
    authorized_keys:
      - key: "{{ secret_gbrown_sshkey }}"
  - name: root
    authorized_keys:
      - key: "{{ secret_root_sshkey }}"

# geerlingguy.docker
docker_install_compose: false
docker_install_compose_plugin: true 
docker_users: 
  - "{{ main_username }}"

# GitHub
github_api_user: 'glennbrown'

# htop
htop_users:
  - homedir: "/home/{{ main_username }}"

# prometheus.prometheus.node_exporter
node_exporter_textfile_dir: /var/lib/node-exporter
node_exporter_version: 1.8.2
node_exporter_system_group: prometheus
node_exporter_system_user: prometheus

# compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID=99
  - PGID=100
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"
