---

# grog.group
group_list:
  - name: gbrown
    gid: 1000

# grog.user
user_list:
  - name: gbrown
    uid: 1000
    group: gbrown
    groups:
      - adm
      - wheel
      - users
      - cdrom
      - video
    password: "{{ secret_gbrown_pass }}"
    comment: "Glenn Brown"

#grog.package
package_list:
  - name: epel-release
  - name: bash-completion
  - name: bc
  - name: PackageKit-command-not-found
  - name: curl
  - name: dialog
  - name: bind-utils
  - name: git
  - name: gnupg2
  - name: gawk
  - name: htop
  - name: iotop
  - name: iftop
  - name: jq
  - name: mc
  - name: ncdu
  - name: neofetch
  - name: net-tools
  - name: openssh-server
  - name: python3
  - name: python3-pip
  - name: python3-setuptools
  - name: pv
  - name: tmux
  - name: wget
  - name: sudo
  - name: tree 
  - name: unzip
  - name: p7zip
  - name: p7zip-plugins
  - name: vim-enhanced
  - name: zip