---

apt_source_mode: modern

# traefik
traefik_debug_log: true
traefik_acme: true
traefik_acme_staging: true
traefik_access_log: true
traefik_extra_entrypoints:
  - name: irc
    port: '7010'

# ZNC
znc_user: "{{ main_username }}"
znc_group: "{{ main_groupname }}"
znc_config_root: "{{ appdata_path }}/znc"

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID={{ main_uid }}
  - PGID={{ main_gid }}
appdata_path: "/home/{{ main_username }}/appdata"
container_config_path: /config

container_networks:
  ###
  - network_name: traefik
    active: true
    external: true

containers:
  ###
  - service_name: traefik
    active: true
    image: traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ appdata_path }}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "{{ appdata_path }}/traefik/config:/etc/traefik/config:ro"
      - "{{ appdata_path }}/traefik/acme.json:/etc/traefik/acme.json"
      - "{{ appdata_path }}/traefik/log:/var/log"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 7010:7010
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.traefik.rule=Host(`{{ ansible_hostname }}.{{ local_domain }}`)"'
      - '"traefik.http.routers.traefik.entrypoints=web"'
      - '"traefik.http.middlewares.traefik-auth.basicauth.users={{ traefik_dashboard_auth }}"'
      - '"traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"'
      - '"traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"'
      - '"traefik.http.routers.traefik.middlewares=traefik-https-redirect"'
      - '"traefik.http.routers.traefik-secure.entrypoints=websecure"'
      - '"traefik.http.routers.traefik-secure.rule=Host(`{{ ansible_hostname }}.{{ local_domain }}`)"'
      - '"traefik.http.routers.traefik-secure.middlewares=traefik-auth"'
      - '"traefik.http.routers.traefik-secure.tls=true"'
      - '"traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"'
      - '"traefik.http.routers.traefik-secure.service=api@internal"'
  ###
  - service_name: nginxhello
    active: true
    image: nginxdemos/nginx-hello
    container_name: nginxhello
    include_global_env_vars: false
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.nginxhello.entrypoints=websecure"'
      - '"traefik.http.routers.nginxhello.rule=Host(`nginxhello.{{ local_domain }}`)"'
      - '"traefik.http.routers.nginxhello.tls=true"'
      - '"traefik.http.routers.nginxhello.tls.certresolver=cloudflare"'
      - '"traefik.http.services.nginxhello.loadbalancer.server.port=8080"'
  ###  
  - service_name: whoami
    active: true
    image: traefik/whoami
    container_name: whoami
    include_global_env_vars: false
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.whoami.entrypoints=websecure"'
      - '"traefik.http.routers.whoami.rule=Host(`whoami.{{ local_domain }}`)"'
      - '"traefik.http.routers.whoami.tls=true"'
      - '"traefik.http.routers.whoami.tls.certresolver=cloudflare"'
  ###  
  - service_name: nginxtest
    active: true
    image: lscr.io/linuxserver/nginx
    container_name: nginxtest
    include_global_env_vars: false
    networks:
      - traefik
    volumes:
      - "{{ appdata_path }}/nginxtest:{{ container_config_path }}"
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.nginxtest.entrypoints=websecure"'
      - '"traefik.http.routers.nginxtest.rule=Host(`nginxtest.{{ local_domain }}`)"'
      - '"traefik.http.routers.nginxtest.tls=true"'
      - '"traefik.http.routers.nginxtest.tls.certresolver=cloudflare"'
      - '"traefik.http.services.nginxtest.loadbalancer.server.port=443"'
      - '"traefik.http.services.nginxtest.loadbalancer.server.scheme=https"'
  ###
  - service_name: znc
    active: true
    image: znc
    container_name: znc
    user: "{{ main_uid }}:{{ main_gid }}"
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
    volumes:
      - "{{ appdata_path }}/znc:/znc-data"
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.zncweb.rule=Host(`znc.{{ local_domain }}`)"'
      - '"traefik.http.routers.zncweb.entrypoints=websecure"'
      - '"traefik.http.routers.zncweb.tls=true"'
      - '"traefik.http.routers.zncweb.tls.certresolver=cloudflare"'
      - '"traefik.http.services.zncweb.loadbalancer.server.port=6501"'
      - '"traefik.tcp.routers.zncirc.rule=HostSNI(`znc.{{ local_domain }}`)"'
      - '"traefik.tcp.routers.zncirc.entrypoints=irc"'
      - '"traefik.tcp.routers.zncirc.tls=true"'
      - '"traefik.tcp.routers.zncirc.tls.certresolver=cloudflare"'
      - '"traefik.tcp.services.zncirc.loadbalancer.server.port=6502"'
