services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    volumes:
      - ~/.config/ntfy:/var/lib/ntfy
    environment:
      TZ: {{ ntp_timezone }}
      NTFY_BASE_URL: https://ntfy.{{ public_domain_1 }}
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
    ports:
      - 8080:80
    command: serve
    restart: unless-stopped
    