services:       
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.uid }}
    volumes:
      - {{ appdata_path }}/prowlarr:/config
    ports:
      - 9696:9696
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.uid }}
    volumes:
      - {{ appdata_path }}/sonarr:/config
      - {{ scratch_path }}/downloads:/downloads
      - media:{{ media_path }}
    ports:
      - 8989:8989
    depends_on:
      - sabnzbd
      - qbittorrent
      - prowlarr
    restart: always
      
  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.uid }}
    volumes:
      - {{ appdata_path }}/radarr:/config
      - {{ scratch_path }}/downloads:/downloads
      - media:{{ media_path }}
    ports:
      - 7878:7878
    depends_on:
      - sabnzbd
      - prowlarr
      - qbittorrent
    restart: always
