services:
  kms:
    image: ghcr.io/py-kms-organization/py-kms
    container_name: kms
    hostname: kms
    environment:
      TZ: {{ ntp_timezone }}
    volumes:
      - {{ appdata_path }}/kms/db:/home/py-kms/db
    ports:
      - 1688:1688
    restart: unless-stopped
  
  speedtest:
    image: ghcr.io/librespeed/speedtest:5.4.1
    container_name: speedtest
    environment:
      TZ: {{ ntp_timezone }}
      MODE: standalone
      TELEMETRY: true
    volumes:
      - {{ appdata_path }}/speedtest/db:/database
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.{{ local_domain }}`)"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.routers.speedtest.tls.certresolver=cloudflare"

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.50.23
    container_name: changedetection
    environment:
      TZ: {{ ntp_timezone }}
      WEBDRIVER_URL: http://selenium:4444
      #PLAYWRIGHT_DRIVER_URL: ws://browserless-chrome:3000/chrome?launch={"defaultViewport":{"height":1080,"width":1920},"headless":false,"stealth":true}&blockAds=true
      BASE_URL: https://changedetection.{{ local_domain }}
    volumes:
      - {{ appdata_path }}/changedetection:/datastore
    depends_on:
      - browserless-chrome
      - selenium
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changedetection.rule=Host(`changedetection.{{ local_domain }}`)"
      - "traefik.http.routers.changedetection.tls=true"
      - "traefik.http.routers.changedetection.tls.certresolver=cloudflare"
    
  browserless-chrome:
    image: ghcr.io/browserless/chrome:v2.37.0
    container_name: browserless-chrome
    environment:
      TZ: {{ ntp_timezone }}
      ENABLE_DEBUGGER: false
      TIMEOUT: 300000
      MAX_CONCURRENT_SESSIONS: 10
      CHROME_REFRESH_TIME: 600000
    volumes:
      - {{ appdata_path }}/changedetection:/datastore
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:141.0
    container_name: selenium
    environment:
      TZ: {{ ntp_timezone }}
      SE_NODE_MAX_SESSIONS: 4
    shm_size: 2g
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.selenium.rule=Host(`selenium.{{ local_domain }}`)"
      - "traefik.http.services.selenium.loadbalancer.server.port=7900"
      - "traefik.http.routers.selenium.tls=true"
      - "traefik.http.routers.selenium.tls.certresolver=cloudflare"
