[linux]
thor
skidblad
rufus
celtic ansible_host=celtic.sparrow-fiordland.ts.net

[mac]
odin

[proxmox]
pve1 ansible_user=root

[all:vars]
ansible_user=gbrown
ansible_python_interpreter=/usr/bin/python3
