---
# Quick Playbook to upgrade a Proxmox Debian Bookworm LXC to Trixie
- hosts: all
  remote_user: root
  tasks:
    - name: Ensure python3-apt is installed
      ansible.builtin.package:
        name: python3-apt
        state: present

    - name: Update Bookworm packages to current
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true
    
    - name: Update sources.list
      ansible.builtin.copy:
        backup: true
        content: '# Debian sources have moved to /etc/apt/sources.list.d/debian.sources'
        dest: /etc/apt/sources.list

    # the deb822_repository module does not support adding two repos to the same file
    - name: Create debian.sources file
      ansible.builtin.copy:
        content: |
          Types: deb
          URIs: http://deb.debian.org/debian/
          Suites: trixie trixie-updates
          Components: main contrib non-free non-free-firmware
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

          Types: deb
          URIs: http://security.debian.org/debian-security/
          Suites: trixie-security
          Components: main contrib non-free non-free-firmware
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
        dest: /etc/apt/sources.list.d/debian.sources
    
    - name: Update existing packages only
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
    
    - name: Full upgrade to trixie
      ansible.builtin.apt:
        upgrade: full
    
    - name: Reboot host
      ansible.builtin.reboot:
        
