roles:
  # IronicBadgers Roles
  - src: https://github.com/glennbrown/ansible-role-docker-compose-generator.git
    name: ironicbadger.docker_compose_generator
    scm: git
  - src: https://github.com/ironicbadger/ansible-role-figurine.git
    name: ironicbadger.figurine
    scm: git
  - src: https://github.com/glennbrown/ansible-role-snapraid.git
    name: ironicbadger.snapraid
    scm: git

  # Jeff Geerling's Roles
  - src: geerlingguy.docker
    version: 7.2.0
  - src: geerlingguy.ntp
    version: 2.5.0
  - src: geerlingguy.security
    version: 2.3.0

  # Grog Roles
  - src: grog.package
    version: v1.4.0
  - src: grog.user
    version: v1.3.1
  - src: grog.group
    version: v1.1.2
  - src: grog.authorized-key
    version: v1.1.5

  # Tailscale
  - src: artis3n.tailscale
    version: v4.5.0