---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
      tags: ['bootstrap']
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'
  roles:
    - role: grog.group
      tags: ['bootstrap']
    - role: grog.user
      tags: ['bootstrap']
    - role: grog.authorized-key
      tags: ['bootstrap']

# Proxmox Server
- hosts: pve
  become: true
  roles:
    - role: glennbrown.mounts
    - role: glennbrown.proxmox
    - role: glennbrown.proxmox-nag-removal
    - role: ironicbadger.figurine

# Media Collection and Distribution Server (Debian LXC)
- hosts: odin
  become: true
  pre_tasks:
    - name: Ensure appdata exists
      file:
        path: "{{ appdata_path }}"
        state: directory
        mode: 0775
        group: users
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: glennbrown.mounts
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine 
    - role: glennbrown.tailscale
    - role: glennbrown.traefik
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Apps and Tools Server (Debian VM)
- hosts: thor
  become: true
  pre_tasks:
    - name: Make sure appdata permissions are correct
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
        group: users
      loop:
        - "{{ appdata_path }}"
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine 
    - role: glennbrown.traefik
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Cloud VPS
- hosts: celtic
  become: true
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: geerlingguy.security
    - role: glennbrown.tailscale
    - role: geerlingguy.docker
    - role: ctop
    - role: glennbrown.oracle-cloud-agent
    - role: glennbrown.firewall
    - role: ironicbadger.figurine
    - role: glennbrown.certbot
      tags: ['certs']
    - role: glennbrown.nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
