---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'

# Proxmox
- hosts: pve
  become: true
  pre_tasks:
    - name: Disable proxmox enterprise repo
      replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb https://enterprise\.proxmox\.com/debian/pve bookworm pve-enterprise'
        replace: '#deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
      notify: Update apt cache
    - name: Disable proxmox enterprise ceph repo
      replace:
        path: /etc/apt/sources.list.d/ceph.list
        regexp: '^deb https://enterprise\.proxmox\.com/debian/ceph-quincy bookworm enterprise'
        replace: '#deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
      notify: Update apt cache
    - name: Switch to proxmox community repo
      apt_repository:
        filename: /etc/apt/sources.list.d/pve-no-subscription
        repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present
      notify: Update apt cache
    - name: Force apt cache update
      meta: flush_handlers
  roles:
    - role: apt-mirror
    - role: base
    - role: proxmox_nag_removal
    - role: grog.package
    - role: geerlingguy.ntp
    - role: bash_aliases
    - role: pve
      tags: provision
    - role: ironicbadger.figurine
  handlers:
    - name: Update apt cache
      apt:
        update_cache: yes

### LXC/VMs/VPS
- hosts: odin
  become: true
  pre_tasks:
    - name: Use legacy iptables
      community.general.alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      loop:
        - { name: iptables, path: '/usr/sbin/iptables-legacy' }
        - { name: ip6tables, path: '/usr/sbin/ip6tables-legacy' }
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: bash_aliases
    - role: odin
    - role: ctop
    - role: ironicbadger.figurine
    - role: ironicbadger.docker-compose-generator
      tags: compose

- hosts: thor
  become: true
  roles:
    - role: grog.package
    - role: bash_aliases
    - role: thor
    - role: certbot
      tags: certs
    - role: nginx
      tags: web
    - role: ironicbadger.figurine

- hosts: heimdall
  become: true
  pre_tasks:
    - name: Use legacy iptables
      community.general.alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      loop:
        - { name: iptables, path: '/usr/sbin/iptables-legacy' }
        - { name: ip6tables, path: '/usr/sbin/ip6tables-legacy' }
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: bash_aliases
    - role: heimdall
    - role: ctop
    - role: ironicbadger.figurine
    - role: ironicbadger.docker-compose-generator
      tags: compose

- hosts: wayland
  become: true
  pre_tasks:
    - name: Use legacy iptables
      community.general.alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      loop:
        - { name: iptables, path: '/usr/sbin/iptables-legacy' }
        - { name: ip6tables, path: '/usr/sbin/ip6tables-legacy' }
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: bash_aliases
    - role: wayland
    - role: ctop
    - role: ironicbadger.figurine
    - role: ironicbadger.docker-compose-generator
      tags: compose

- hosts: celtic
  become: true
  roles:
    - role: grog.package
    - role: geerlingguy.security
    - role: artis3n.tailscale
    - role: bash_aliases
    - role: geerlingguy.docker
    - role: ctop
    - role: ocagent
    - role: celtic
    - role: certbot
      tags: certs
    - role: nginx
      tags: web
    - role: ironicbadger.docker-compose-generator
      tags: compose
    - role: ironicbadger.figurine
