---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
      when: ansible_system == 'Linux'
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'

# Mac Mini Server
- name: Configure Mac Mini Server
  hosts: odin
  roles:
    - role: grog.authorized-key
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: glennbrown.certbot
      tags: ['certs']
    - role: glennbrown.nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Cloud VPS
- name: Configure Cloud VPS
  become: true
  hosts: celtic
  roles:
    - role: grog.group
      tags: ['bootstrap']
    - role: grog.user
      tags: ['bootstrap']    
    - role: grog.authorized-key
    - role: grog.package
    - role: geerlingguy.security
    - role: glennbrown.tailscale
    - role: geerlingguy.docker
    - role: ctop
    - role: glennbrown.oracle-cloud-agent
    - role: glennbrown.firewall
    - role: ironicbadger.figurine
      tags: ['bootstrap']
    - role: glennbrown.certbot
      tags: ['certs']
    - role: glennbrown.nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
