---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
      tags: ['bootstrap']
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'
  roles:
    - role: grog.group
      tags: ['bootstrap']
      when: ansible_os_family != 'Darwin'
    - role: grog.user
      tags: ['bootstrap']
      when: ansible_os_family != 'Darwin'
    - role: grog.authorized-key
      tags: ['bootstrap']

# Mac Mini Server
- hosts: odin
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['packages']
    - role: geerlingguy.dotfiles
    - role: geerlingguy.mac.mas
      tags: ['mas']
    - role: geerlingguy.mac.dock
      vars:
        homebrew_path: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin"
      environment:
        PATH: "{{ homebrew_path }}:{{ ansible_env.PATH }}"
      tags: ['dock']
    - role: glennbrown.macos
      tags: ['defaults']
    - role: glennbrown.certbot
      tags: ['certs']

# Docker VM Host running on the Mac Mini
- hosts: thor
  become: true
  pre_tasks:
    - name: Make sure appdata/scratch permissions are correct
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
        group: users
      loop:
        - "{{ appdata_path }}"
        - "{{ scratch_path }}"
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: glennbrown.mounts
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine 
    - role: glennbrown.traefik
      tags: ['proxy']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Cloud VPS
- hosts: celtic
  become: true
  roles:
    - role: grog.package
      tags: ['packages']
    - role: geerlingguy.security
    - role: glennbrown.tailscale
    - role: geerlingguy.docker
    - role: ctop
    - role: glennbrown.oracle-cloud-agent
    - role: glennbrown.firewall
    - role: ironicbadger.figurine
    - role: glennbrown.certbot
      tags: ['certs']
    - role: glennbrown.nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
