---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'
  roles:
    - role: grog.group
      tags: ['bootstrap']
    - role: grog.user
      tags: ['bootstrap']
    - role: grog.authorized-key
      tags: ['bootstrap']
    - role: grog.package
      tags: ['packages']

# Home Server
- name: Configure Home Server
  become: true
  hosts: odin
  pre_tasks:
    - name: Load Kernel modules
      modprobe:
        name: '{{ item }}'
        state: present
        persistent: present
      loop:
        - nct6775
        - drivetemp
  roles:
    - role: ironicbadger.mounts
    - role: geerlingguy.docker
    - role: ironicbadger.figurine
    - role: glennbrown.tailscale
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Cloud VPS
- name: Configure Cloud VPS
  become: true
  hosts: celtic
  roles:
    - role: geerlingguy.security
    - role: glennbrown.tailscale
    - role: geerlingguy.docker
    - role: ctop
    - role: glennbrown.oracle-cloud-agent
    - role: glennbrown.firewall
    - role: ironicbadger.figurine
    - role: glennbrown.certbot
      tags: ['certs']
    - role: glennbrown.nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
