---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone: 
        name: "{{ ntp_timezone }}"
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'
  roles:
    - role: grog.group
      tags: ['bootstrap']
    - role: grog.user
      tags: ['bootstrap']
    - role: grog.authorized-key
      tags: ['bootstrap']

# Proxmox setup
- hosts: pve
  become: true
  roles:
    - role: proxmox
    - role: proxmox-nag-removal
    - role: ironicbadger.figurine
      
# LXC for Media Servers that need iGPU access
- hosts: odin
  become: true
  pre_tasks:
    - name: Make sure appdata permissions are correct
      file:
        path: "{{ appdata_path }}"
        state: directory
        mode: 0775
        group: users
  roles:
    - role: grog.package
      tags: ['packages']
    - role: drivemounts
    - role: geerlingguy.docker
    - role: ironicbadger.figurine 
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Media distribution/collection 
- hosts: bifrost
  become: true
  pre_tasks:
    - name: Make sure appdata/scratch permissions are correct
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
        group: users
      loop:
        - "{{ appdata_path }}"
        - "{{ scratch_path }}"
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: drivemounts
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine 
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Nginx Reverse Proxy
- hosts: thor
  become: true
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: ironicbadger.figurine
    - role: certbot
      tags: ['certs']
    - role: nginx
      tags: ['web']

# Tools Server
- hosts: wayland
  become: true
  pre_tasks:
    - name: Make sure appdata/scratch permissions are correct
      file:
        path: "{{ appdata_path }}"
        state: directory
        mode: 0775
        group: users
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']

# Monitoring Server
- hosts: heimdall
  become: true
  pre_tasks:
    - name: Make sure appdata/scratch permissions are correct
      file:
        path: "{{ appdata_path }}"
        state: directory
        mode: 0775
        group: users
  roles:
    - role: apt-mirror
    - role: grog.package
      tags: ['packages']
    - role: qemu-guest-agent
    - role: geerlingguy.docker
    - role: ctop
    - role: ironicbadger.figurine
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
  
# Cloud VPS
- hosts: celtic
  become: true
  roles:
    - role: grog.package
      tags: ['packages']
    - role: geerlingguy.security
    - role: glennbrown.tailscale
    - role: geerlingguy.docker
    - role: ctop
    - role: glennbrown.oracle-cloud-agent
    - role: glennbrown.firewall
    - role: ironicbadger.figurine
    - role: certbot
      tags: ['certs']
    - role: nginx
      tags: ['web']
    - role: ironicbadger.docker-compose-generator
      tags: ['compose']
