---
#
###############################################################################
# Install Miscellaneous Tools
###############################################################################
#

- name: Set mergerfs-tools binary location
  ansible.builtin.stat:
    path: /usr/local/bin/mergerfs.ctl
  register: mergerfs_tools_binary

- name: Determine if mergerfs-tools are installed
  ansible.builtin.set_fact:
    mergerfs_tools_installed: "{{ mergerfs_tools_binary.stat.exists|default(false) }}"

- name: git clone mergerfs-tools
  ansible.builtin.git:
    repo: https://github.com/trapexit/mergerfs-tools.git
    dest: /tmp/mergerfs-tools
  when: not mergerfs_tools_installed

- name: Install mergerfs-tools
  ansible.builtin.command:
    chdir: /tmp/mergerfs-tools
    cmd: make install
  when: not mergerfs_tools_installed