---

- name: Ensure destination for compose file exists
  file:
    path: "{{ docker_compose_generator_output_path }}"
    state: directory

- name: Write docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_generator_output_path }}/docker-compose.yml"
    owner: "{{ docker_compose_generator_uid }}"
    group: "{{ docker_compose_generator_gid }}"