---

- name: Configure DNS server options
  uci:
    command: set
    key: "dhcp.@dnsmasq[0]"
    value:
      cachesize: "{{ openwrt_dnsmasq_cachesize }}"
      localservice: "{{ openwrt_dnsmasq_localservice }}"
      local: "/{{ openwrt_dnsmasq_domain }}/"
      domain: "{{ openwrt_dnsmasq_domain }}"

- name: Configure interface for dnsmasq
  uci:
    command: add_list
    key: "dhcp.cfg01411c.interface"
    value: "{{ openwrt_dnsmasq_listen }}"

#turning off rebind, don't really need it for internal use
- name: Turn off DNS Rebind Protection
  uci:
    command: set
    key: "dhcp.@dnsmasq[0]"
    value:
      rebind_protection: '0'
  register: disable_rebind

- name: Delete rebind localhost config entry
  uci:
    command: delete
    key: dhcp.cfg01411c.rebind_localhost
  when: disable_rebind.changed
  
- name: Configure DHCP options
  uci:
    command: set
    key: "dhcp.lan"
    value:
      start: "{{ openwrt_dhcp_start }}"
      limit: "{{ openwrt_dhcp_limit }}"
      leasetime: "{{ openwrt_dhcp_leasetime }}"

- name: Configure DHCP static leases
  uci:
    command: section
    config: dhcp
    type: host
    find:
      name: "{{ item.hostname }}"
    value:
      mac: "{{ item.mac }}"
      ip: "{{ item.ip }}"
      dns: '1'
  with_items: "{{ openwrt_dhcp_static_leases }}"
  when: openwrt_dhcp_static_leases is defined

- name: Configure DNS Hostnames
  uci:
    command: section
    config: dhcp
    type: domain
    find:
      name: "{{ item.hostname }}"
    value:
      ip: "{{ item.ip }}"
  with_items: "{{ openwrt_dns_hostnames }}"
  when: openwrt_dns_hostnames is defined

- name: Configure DNS Overrides
  uci:
    command: add_list
    key: "dhcp.cfg01411c.address"
    value: "/{{ item.custom_dns }}/{{ item.ip }}"
    unique: true
  with_items: "{{ openwrt_dns_overrides }}"
  when: openwrt_dns_overrides is defined

- name: Commit changes
  uci:
    command: commit
  notify: restart dhcp