---

- ansible.builtin.include_role:
    name: gekmihesg.openwrt

- name: Check for duplicate reservations
  ansible.builtin.include_tasks: duplicate_checks.yml

- name: Modify Network configuration
  ansible.builtin.include_tasks: network.yml

- name: Modify DHCP configuration
  ansible.builtin.include_tasks: dhcp.yml
    