---
proxmox_kernel_modules: []
proxmox_packages:
  - apt-file
  - aptitude 
  - btop
  - command-not-found
  - cpufetch
  - fwupd
  - htop
  - intel-microcode
  - inxi
  - jq
  - lm-sensors
  - mc
  - nvme-cli
  - smartmontools
  - python3-apt
  - python3-debian
  - sudo
  - tmux
  - vim