---

- name: caddy | copy systemd service file
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root

- name: caddy | ensure config directory exists
  ansible.builtin.file:
    path: "{{ caddy_config_path }}"
    state: directory

- name: caddy | ensure log directory exists
  ansible.builtin.file:
    path: "{{ caddy_log_path }}"
    state: directory

- name: caddy | copy Caddyfile from template file
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_config_path }}/Caddyfile"
    owner: root
    group: root
  notify: reload caddy

- name: caddy | enable caddy service at boot
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    daemon_reload: true