---

- name: Ensure config directory exists
  ansible.builtin.file:
    dest: "{{ appdata_path }}/traefik"
    state: directory
    owner: root
    group: users
    mode: 0775

- name: Check if acme file exists already
  ansible.builtin.stat:
    path: "{{ appdata_path }}/traefik/acme.json"
  register: acme_json_file

- name: Ensure acme file exists
  ansible.builtin.file:
    dest: "{{ appdata_path }}/traefik/acme.json"
    state: touch
    owner: root
    group: root
    mode: 0600
  when: not acme_json_file.stat.exists

- name: Copy traefik config file from template
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ appdata_path }}/traefik/traefik.yml"
    owner: root
    group: users
    mode: 0664
  tags: traefik

- name: Create traefik file provider directory
  ansible.builtin.file:
    dest: "{{ appdata_path }}/traefik/rules"
    state: directory
    owner: root
    group: users
    mode: 0775
  tags: traefik
  when: traefik_file_providers

- name: Copy traefik file provider rules
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "{{ appdata_path }}/traefik/rules/{{ item.name }}"
    owner: root
    group: users
    mode: 0664
  loop: "{{ traefik_file_providers }}"
  tags: traefik
  when: traefik_file_providers