services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID={{ me.uid }}
      - TORRENTING_PORT=6881
      - WEBUI_PORT=8088
    volumes:
      - {{ appdata_path }}/qbittorrent:/config
      - {{ scratch_path }}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    restart: always
    