services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy
    volumes:
      - "{{ appdata_path }}/nfty:/var/lib/ntfy"
    environment:
      - TZ={{ ntp_timezone }}
      - NTFY_BASE_URL=https://ntfy.{{ public_domain_1 }}
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
    command: serve
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.rule=Host(`ntfy.{{ public_domain_1 }}`)
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=cloudflare
      - traefik.http.routers.ntfy.tls.domains[0].main={{ public_domain_1 }}
      - traefik.http.routers.ntfy.tls.domains[0].sans=*.{{ public_domain_1 }}