services: 
  glenn-blog:
    image: ghost:5.105.0-alpine
    container_name: glenn-blog
    environment:
      - TZ={{ ntp_timezone }}
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=glenn-blog-db
      - database__connection__user={{ glennblog_db_user }}
      - database__connection__password={{ glennblog_db_pass }}
      - database__connection__database=ghost
      - url=https://www.{{ public_domain_2 }}
    volumes:
      - "{{ appdata_path }}/glenn-blog/content:/var/lib/ghost/content"
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
      - default
    depends_on:
      - glenn-blog-db
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.glennblog.rule=Host(`www.{{ public_domain_2 }}`)
      - traefik.http.routers.glennblog.entrypoints=websecure
      - traefik.http.routers.glennblog.tls=true
      - traefik.http.routers.glennblog.tls.certresolver=cloudflare
      - traekik.http.routers.glennblog.tls.domains[0].main={{ public_domain_2 }}
      - traekik.http.routers.glennblog.tls.domains[0].sans=*.{{ public_domain_2 }}
  glenn-blog-db:
    image: mysql:8.4.3
    container_name: glenn-blog-db
    environment:
      - TZ={{ ntp_timezone }}
      - MYSQL_ROOT_PASSWORD={{ mysql_root_pass }}
    volumes:
      - "{{ appdata_path }}/glenn-blog/db:/var/lib/mysql"
    networks:
      - default
    restart: unless-stopped