---

- name: Create config directories
  file:
    path: "/home/{{ main_username }}/{{ item }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - 'appdata/hass'
    - scripts
