---
- name: Load distribution specifc vars
  ansible.builtin.include_vars:
    file: "{{ ansible_facts.distribution | lower }}.yml"

- name: Setup apt mirrors
  ansible.builtin.include_tasks:
    file: "setup-{{ ansible_facts.distribution | lower }}.yml"

- name: Force update apt cache
  ansible.builtin.meta: flush_handlers
