---

- name: Update sources.list
  become: true
  template:
    src: sources.list.ubuntu.j2
    dest: /etc/apt/sources.list
  register: ubuntu_apt_config_legacy
  when: apt_source_mode == 'legacy'

- name: Replace sources.list
  become: true
  copy:
    src: ubuntu.sources.list
    dest: /etc/apt/sources.list
  when: apt_source_mode == 'modern'
    
- name: Install ubuntu.sources
  become: true
  template:
    src: ubuntu.sources.j2
    dest: /etc/apt/sources.list.d/ubuntu.sources
  register: ubuntu_apt_config_modern
  when: apt_source_mode == 'modern'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: ubuntu_apt_config_legacy.changed or ubuntu_apt_config_modern.changed