---
legacy_apt_sources: |
  deb http://deb.debian.org/debian/ {{ ansible_facts.distribution_release }} {{ debian_components }}
  deb-src http://deb.debian.org/debian {{ ansible_facts.distribution_release }} {{ debian_components }}

  deb http://deb.debian.org/debian {{ ansible_facts.distribution_release }}-updates {{ debian_components }}
  deb-src http://deb.debian.org/debian {{ ansible_facts.distribution_release }}-updates {{ debian_components }}

  deb http://deb.debian.org/debian {{ ansible_facts.distribution_release }}-backports {{ debian_components }}
  deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports {{ debian_components }}

  deb http://security.debian.org {{ ansible_facts.distribution_release }}-security {{ debian_components }}
  deb-src http://security.debian.org {{ ansible_facts.distribution_release }}-security {{ debian_components }}

deb822_apt_sources: |
  Types: deb deb-src
  URIs: http://deb.debian.org/debian/
  Suites: {{ ansible_facts.distribution_release }} {{ ansible_facts.distribution_release }}-updates {{ ansible_facts.distribution_release }}-backports
  Components: {{ debian_components }}
  Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

  Types: deb deb-src
  URIs: http://security.debian.org/debian-security/
  Suites: {{ ansible_facts.distribution_release }}-security
  Components: {{ debian_components }}
  Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
