---
# bash_aliases
bash_aliases:
  - alias: "bashreload"
    command: "source ~/.bashrc && echo Bash config reloaded;"
  - alias: "dir"
    command: "ls --color=auto --format=vertical"
  - alias: "egrep"
    command: "egrep --color=auto"
  - alias: "fgrep"
    command: "fgrep --color=auto"
  - alias: "grep"
    command: "grep --color=auto"
  - alias: "l"
    command: "ls -CF --color=auto"
  - alias: "la"
    command: "ls -A --color=auto"
  - alias: "ll"
    command: "ls -l --color=auto"
  - alias: "vdir"
    command: "ls --color=auto --format=long"
  - alias: "mc"
    command: "/usr/share/mc/bin/mc-wrapper.sh"

bash_apt_aliases:
  - alias: agi
    command: "sudo apt install "
  - alias: agr
    command: "sudo apt remove "
  - alias: agu
    command: "sudo apt update && sudo apt upgrade"

bash_docker_aliases:
  - alias: "dtail"
    command: "docker logs -tf --tail='50' "
  - alias: "dstop"
    command: "docker stop `docker ps -aq`"
  - alias: "drm"
    command: "docker rm `docker ps -aq`"
  - alias: "dcp"
    command: "docker compose -f ~/compose.yaml "
  - alias: "dcporph"
    command: "docker compose -f ~/compose.yaml --remove-orphans "
  - alias: "dprune"
    command: "docker image prune"
  - alias: "dprunesys"
    command: "docker system prune --all"
  
bash_systemctl_aliases:
  - alias: sc-start
    command: "sudo systemctl start "
  - alias: sc-stop
    command: "sudo systemctl stop "
  - alias: sc-restart
    command: "sudo systemctl restart "
  - alias: sc-enable
    command: "sudo systemctl enable "
  - alias: sc-disable
    command: "sudo systemctl disable "
  - alias: sc-status
    command: "sudo systemctl status "
  - alias: sc-reload
    command: "sudo systemctl daemon-reload"