---

# Sudo Password for Become
ansible_become_password: "{{ lookup('community.general.onepassword', 'Ansible Become', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# User Account Password
secret_gbrown_pass: "{{ ansible_become_password | password_hash('sha512') }}"

# Cloudflare
cloudflare_account_id: "{{ lookup('community.general.onepassword', 'Cloudflare Account ID', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
cloudflare_lego_api_token: "{{ lookup('community.general.onepassword', 'Lego API Token', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
cloudflare_certbot_api_token: "{{ lookup('community.general.onepassword', 'Certbot API Token', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
cloudflare_traefik_api_token: "{{ lookup('community.general.onepassword', 'Cloudflare Traefik API Token', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# Traefik
traefik_dashboard_password: "{{ lookup('community.general.onepassword', 'Traefik Dashboard', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# Github
github_api_pass: "{{ lookup('community.general.onepassword', 'Github API Token', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# MySQL
mysql_root_pass: "{{ lookup('community.general.onepassword', 'MySQL root', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
glennblog_db_user: "{{ lookup('community.general.onepassword', 'Glenn Blog DB', field='username', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
glennblog_db_pass: "{{ lookup('community.general.onepassword', 'Glenn Blog DB', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# Synology CIFS
secret_synology_gbrown: "{{ lookup('community.general.onepassword', 'Synology CIFS Access', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# Plex Claim Token
plex_claim_token: "{{ lookup('community.general.onepassword', 'Plex Claim Token', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# Jellystat
jellystat_postgres_pass: "{{ lookup('community.general.onepassword', 'Jellystat DB', field='password', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
jellystat_jwt_secret: "{{ lookup('community.general.onepassword', 'Jellystat JWT Secret', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"

# ntfy
ntfy_user: "{{ lookup('community.general.onepassword', 'Ntfy', field='username') }}"
ntfy_pass: "{{ lookup('community.general.onepassword', 'Ntfy', field='password') }}"

# Beszel
odin_agent_key: "{{ lookup('community.general.onepassword', 'beszel-agent-odin', field='Public Key', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
odin_agent_token: "{{ lookup('community.general.onepassword', 'beszel-agent-odin', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
thor_agent_key: "{{ lookup('community.general.onepassword', 'beszel-agent-thor', field='Public Key', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"
thor_agent_token: "{{ lookup('community.general.onepassword', 'beszel-agent-thor', field='credential', vault='Ansible Secrets', service_account_token=ansible_op_token) }}"