services:
  traefik:
    image: traefik:3.5.0
    container_name: traefik
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - /etc/traefik/config:/config
      - /etc/traefik/letsencrypt:/letsencrypt
      - /etc/traefik/.htpasswd:/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=info
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/config
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloud.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    extra_hosts:
      - host.docker.internal:172.17.0.1
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`{{ ansible_hostname }}.{{ local_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.add-slash.redirectregex.regex=^(https?://[^/]+/dashboard)$"
      - "traefik.http.middlewares.add-slash.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.add-slash.redirectregex.permanent=true"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`{{ ansible_hostname }}.{{ local_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth,add-slash"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=*.{{ local_domain }}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ local_domain }}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
