---

debian_package_list:
  - apt-file
  - aptitude
  - bash-completion
  - bc
  - debian-goodies
  - bind9-dnsutils
  - btop
  - command-not-found
  - curl
  - dialog
  - htop
  - gawk
  - git
  - gnupg2
  - htop
  - iotop
  - iftop
  - inxi
  - jq
  - mc
  - nano
  - needrestart
  - net-tools
  - nmap
  - pv
  - python3
  - python3-apt
  - python3-debian
  - python3-pip
  - python3-setuptools
  - p7zip-full
  - p7zip-rar
  - screen
  - sudo
  - tmux
  - tree
  - wget
  - vim
  - update-notifier-common
  - unzip
  - zip
  