---
homebrew_user: "{{ me.username }}"
homebrew_group: admin

homebrew_installed_packages:
- name: bash
- name: bash-completion@2
- name: bbrew
- name: brew-cask-completion
- name: btop
- name: bun
- name: cdrtools
- name: coreutils
- name: cpio
- name: cpufetch
- name: ctop
- name: diceware
- name: diffutils
- name: fastfetch
- name: figurine
- name: findutils
- name: fio
- name: ffmpeg
- name: flac
- name: gawk
- name: gcc
- name: gh
- name: gnu-sed
- name: gnu-tar
- name: go
- name: grep
- name: htop
- name: imagemagick
- name: inxi
- name: iperf3
- name: jq
- name: just
- name: lame
- name: lesspipe
- name: lz4
- name: lzo
- name: macmon
- name: mactop
- name: media-info
- name: nano
- name: nanorc
- name: ncurses
- name: neofetch
- name: nmap
- name: perl
- name: php
- name: pipx
- name: pv
- name: qemu
- name: ruby
- name: screenresolution
- name: smartmontools
- name: snappy
- name: socat
- name: sqlite
- name: sshpass
- name: svt-av1
- name: teamookla/speedtest/speedtest
- name: tmux
- name: usbutils
- name: webp
- name: wget
- name: when
- name: x264
- name: x265
- name: xvid
- name: xz
- name: yt-dlp
- name: zsh-autosuggestions
- name: zsh-completions # Install upsteam head version
  state: head
- name: zsh-history-substring-search
- name: zstd
# Rust Tools
- name: diffr # Modern Unix `diff`
- name: difftastic # Modern Unix `diff`
- name: dua-cli # Modern Unix `du`
- name: dust # Modern du
- name: fzf # Fuzzy finder
- name: fd # Find replacement
- name: duf # Modern Unix `df`
- name: entr # Modern Unix `watch`
- name: eza # Moder `ls` replacement
- name: procs # Modern replacement for ps
- name: ripgrep # Modern grep replacement
- name: starship # Prompt bling
- name: tealdeer # Rust re-write of tldr which are community based manpages
- name: uutils-diffutils # Rust rewrite of diffutils
- name: uutils-findutils #Rust rewrite of findutils
- name: zoxide # Modern cd replacment

homebrew_cask_apps:
- name: 1password
- name: 1password-cli
- name: arc
- name: automounterhelper
- name: bbedit
- name: docker-desktop
- name: font-jetbrains-mono
- name: font-jetbrains-mono-nerd-font
- name: font-meslo-lg-nerd-font
- name: ghostty
- name: google-chrome
- name: grandperspective
- name: hazel
- name: keka
- name: kekaexternalhelper
- name: plex-media-server
- name: qbittorrent
- name: sabnzbd
- name: timemachineeditor
- name: utm
- name: visual-studio-code

homebrew_taps:
- glennbrown/tap
- homebrew/command-not-found
- oven-sh/bun
- teamookla/speedtest
- valkyrie00/bbrew
