---
# Services to restart
macos_services:
- Dock
- Finder
- SystemUIServer

# Setting my preferred macOS defaults
macos_default_settings:
# General UI/UX
# Expand save panel by default
- domain: NSGlobalDomain
  key: NSNavPanelExpandedStateForSaveMode
  type: bool
  value: true
# Expand print panel by default
- domain: NSGlobalDomain
  key: PMPrintingExpandedStateForPrint
  type: bool
  value: true
# Disable smart quotes as they’re annoying when typing code
- domain: NSGlobalDomain
  key: NSAutomaticQuoteSubstitutionEnabled
  type: bool
  value: true
# Disable smart dashes as they’re annoying when typing code
- domain: NSGlobalDomain
  key: NSAutomaticDashSubstitutionEnabled
  type: bool
  value: true
# Automatically quit printer app once the print jobs complete
- domain: com.apple.print.PrintingPrefs
  key: "Quit When Finished"
  type: bool
  value: true

# Disable press-and-hold for keys in favor of key repeat
- domain: NSGlobalDomain
  key: ApplePressAndHoldEnabled
  type: bool
  value: false
# Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
# (The KeyRepeat option requires logging out and back in to take effect.)
- domain: NSGlobalDomain
  key: InitialKeyRepeat
  type: int
  value: '20'
- domain: NSGlobalDomain
  key: KeyRepeat
  type: int
  value: '1'
# Disable auto-correct
- domain: NSGlobalDomain
  key: NSAutomaticSpellingCorrectionEnabled
  type: bool
  value: false

# Screenshots
# Save screenshots to iCloud Drive Screenshots folder
- domain: com.apple.screencapture
  key: location
  type: string
  value: "~/Documents/Photos/Screenshots"
# Save as jpg
- domain: com.apple.screencapture
  key: type
  type: string
  value: "jpg"
# Disable shadow on screenshots
- domain: com.apple.screencapture
  key: disable-shadow
  type: bool
  value: true

# Finder
# Show icons for hard drives, servers, and removable media on the desktop
- domain: com.apple.finder
  key: ShowExternalHardDrivesOnDesktop
  type: bool
  value: true
- domain: com.apple.finder
  key: ShowHardDrivesOnDesktop
  type: bool
  value: true
- domain: com.apple.finder
  key: ShowMountedServersOnDesktop
  type: bool
  value: true
- domain: com.apple.finder
  key: ShowRemovableMediaOnDesktop
  type: bool
  value: true
# Finder: Show status bar
- domain: com.apple.finder
  key: ShowStatusBar
  type: bool
  value: true
# Finder: Show Path Bar
- domain: com.apple.finder
  key: ShowPathbar
  type: bool
  value: true
# Finder: Keep Folders on top
- domain: com.apple.finder
  key: _FXSortFoldersFirst
  type: bool
  value: true
# Automatically Empty Recycle bin after 30 days
- domain: com.apple.finder
  key: FXRemoveOldTrashItems
  type: bool
  value: true
# Finder: allow text selection in Quick Look
- domain: com.apple.finder
  key: QLEnableTextSelection
  type: bool
  value: true
# When performing a search, search the current folder by default
- domain: com.apple.finder
  key: FXDefaultSearchScope
  type: string
  value: "SCcf"
# Disable the warning when changing a file extension
- domain: com.apple.finder
  key: FXEnableExtensionChangeWarning
  type: bool
  value: true
# Enable spring loading for directories
- domain: NSGlobalDomain
  key: com.apple.springing.enabled
  type: bool
  value: true
# Remove the spring loading delay for directories
- domain: NSGlobalDomain
  key: com.apple.springing.delay
  type: float
  value: '0.1'
# Avoid creating .DS_Store files on network volumes
- domain: com.apple.desktopservices
  key: DSDontWriteNetworkStores
  type: bool
  value: true
# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
- domain: com.apple.finder
  key: FXPreferredViewStyle
  type: string
  value: "Nlsv"

# Dock, Dashboard and hot corners
# Set the icon size of Dock items
- domain: com.apple.dock
  key: tilesize
  type: float
  value: '42'
# Make Dock icons of hidden applications translucent
- domain: com.apple.dock
  key: showhidden
  type: bool
  value: true
# Autohide Dock
- domain: com.apple.dock
  key: autohide
  type: bool
  value: false
# Speed up hide/show dock animations
- domain: com.apple.dock
  key: autohide-delay
  type: float
  value: '0'
- domain: com.apple.dock
  key: autohide-time-modifier
  type: float
  value: '0.15'
# Use scale effect with dock
- domain: com.apple.dock
  key: mineffect
  type: string
  value: "scale"
# Left Align Dock
- domain: com.apple.dock
  key: orientation
  type: string
  value: "right"
# Don't show recent apps
- domain: com.apple.dock
  key: show-recents
  type: bool
  value: false
# Expose/Mission Control Group Apps
- domain: com.apple.dock
  key: expose-group-apps
  type: bool
  value: true
# Minimize windows into their application’s icon
- domain: com.apple.dock
  key: minimize-to-application
  type: bool
  value: true

# Safari & Webkit
# Enable the Develop menu and the Web Inspector in Safari
- domain: com.apple.safari
  key: IncludeDevelopMenu
  type: bool
  value: true
- domain: com.apple.safari
  key: WebKitDeveloperExtrasEnabledPreferenceKey
  type: bool
  value: true
- domain: com.apple.safari
  key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled"
  type: bool
  value: true
# Add a context menu item for showing the Web Inspector in web views
- domain: NSGlobalDomain
  key: WebKitDeveloperExtras
  type: bool
  value: true
# Show Full URL in Address Bar
- domain: com.apple.safari
  key: ShowFullURLInSmartSearchField
  type: bool
  value: true

# Activity Monitor
# Show the main window when launching Activity Monitor
- domain: com.apple.ActivityMonitor
  key: OpenMainWindow
  type: bool
  value: true
# Show all processes in Activity Monitor
- domain: com.apple.ActivityMonitor
  key: ShowCategory
  type: int
  value: '0'

# App Store
# Disable in-app rating requests from apps downloaded from the App Store.
- domain: com.apple.appstore
  key: InAppReviewEnabled
  type: int
  value: '0'

# Time Machine
# Don't offer new disks for Time Machine backup
- domain: com.apple.TimeMachine
  key: DoNotOfferNewDisksForBackup
  type: bool
  value: true
