---

# ZNC Install
znc_user: ''
znc_group: ''
znc_config_root: ''
znc_version: '1.8.2'
znc_clientbuffer_repo: 'https://github.com/CyberShadow/znc-clientbuffer.git'
znc_palaver_repo: 'https://github.com/cocodelabs/znc-palaver.git'
znc_logsearch_repo: 'https://github.com/pR0Ps/znc-logsearch.git'

# ZNC Global Configuration
znc_max_buffer_size: 100000
znc_listener:
  - {name: irc, ipv4: true, ipv6: false, port: 6502, irc: true, web: false, ssl: false}
  - {name: web, ipv4: true, ipv6: false, port: 6501, irc: false, web: true, ssl: false}

znc_ssl_enable: false
znc_ssl_certfile: "{{ znc_config_root }}/znc.pem"
znc_global_modules:
  - webadmin
  - palaver
  - admindebug
  - adminlog
  - block_motd
  - fail2ban
  - modpython

# ZNC User Definitions
# See http://wiki.znc.in/Configuration
# This should be defined in group_vars
# Passwords can be created using znc --makepass
# znc_users:
#   - name: test
#     password:
#       method: 'sha256'
#       hash: ''
#       salt: ''
#     nick: testuser
#     altnick: testuser_
#     realname: 'Real Test User'
#     admin: true
#     ident: 'testuser'
#     allow: "*"
#     altnick: adminuser_
#     autoclearchanbuffer: true
#     autoclearquerybuffer: true
#     buffer: 100000
#     chanmodes: "+stn"
#     ident: adminuser
#     multiclients: false
#     networks:
#       freenode:
#         server: chat.freenode.net
#         port: 6697
#         ssl: true
#         password: ""
#         channels:
#           - "#freenode"
#         modules:
#           - route_replies
#           - keepnick
#           - clientbuffer
#     modules:
#       - chansaver
#       - controlpanel

