---

- name: Create Docker network
  docker_network:
    name: traefik

- name: Ensure config directories exist
  file:
    dest: "{{ appdata_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - traefik
    - traefik/config
    - traefik/log

- name: Check if acme file exists already
  stat:
    path: "{{ appdata_path }}/traefik/acme.json"
  register: acme_json_file

- name: Ensure acme file exists
  file:
    dest: "{{ appdata_path }}/traefik/acme.json"
    state: touch
    owner: root
    group: root
    mode: 0600
  when: not acme_json_file.stat.exists

- name: Copy traefik config file from template
  template:
    src: traefik.yml.j2
    dest: "{{ appdata_path }}/traefik/traefik.yml"
    owner: root
    group: root
    mode: 0664

- name: Copy traefik tls config file
  template:
    src: tls-config.yml.j2
    dest: "{{ appdata_path }}/traefik/config/tls-config.yml"
    owner: root
    group: root
    mode: 0644

- name: Copy traefik file provider rules
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ appdata_path }}/traefik/config/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ traefik_file_providers }}"
  when: traefik_file_providers is defined