---

- name: traefik | ensure config directory exists
  ansible.builtin.file:
    dest: "{{ appdata_path }}/traefik"
    state: directory
    owner: root
    group: users
    mode: 0775

- name: traefik | check if acme file exists already
  ansible.builtin.stat:
    path: "{{ appdata_path }}/traefik/acme.json"
  register: acme_json_file

- name: traefik | ensure acme file exists
  ansible.builtin.file:
    dest: "{{ appdata_path }}/traefik/acme.json"
    state: touch
    owner: root
    group: root
    mode: 0600
  when: not acme_json_file.stat.exists

- name: traefik | copy traefik config file from template
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ appdata_path }}/traefik/traefik.yml"
    owner: root
    group: users
    mode: 0664
  tags: traefik

- name: traefik | copy traefik file provider rules
  ansible.builtin.template:
    src: "{{ ansible_hostname }}-rules.yml.j2"
    dest: "{{ appdata_path }}/traefik/rules.yml"
    owner: root
    group: users
    mode: 0664
  tags: traefik
  when: traefik_file_provider