---
# some basic variables
main_username: gbrown
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# ironicbadger.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' "}
  - { alias: "dstop", command: "docker stop `docker ps -aq`"}
  - { alias: "drm", command: "docker rm `docker ps -aq`"}
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml --remove-orphans "}
  - { alias: "dprune", command: "docker image prune"}
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;"}
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop "}

# geerlingguy.ntp
ntp_timezone: America/New_York

# grog.package
package_update_cache: yes
package_list:
  - name: zsh
    package_state: absent 
  - name: curl
  - name: git
  - name: bash-completion
  - name: gnupg2
  - name: htop
  - name: jq
  - name: ncdu
  - name: neofetch
  - name: net-tools
  - name: python3
  - name: python3-apt
  - name: python3-pip
  - name: tmux
  - name: wget
  - name: mc
  - name: sudo
  - name: tree
  - name: iotop
  - name: iftop
  - name: zip
  - name: unzip
  - name: p7zip-full
  - name: rar
  - name: unrar

# grog.group
group_list:
  - { name: gbrown, gid: 1000, state: present }

# grog.user
user_list:
  - name: gbrown
    uid: 1000
    group: gbrown
    groups:
      - adm
      - sudo
      - users
      - cdrom
      - dip
      - plugdev
    append: yes
    password: "{{ secret_gbrown_pass }}"
    move_home: yes
    shell: /bin/bash
    comment: "Glenn Brown"
    state: present

# grog.authorized-key
authorized_key_list:
  - name: gbrown
    authorized_keys:
      - key: "{{ secret_gbrown_key }}"

# oh-my-zsh
# users:
#   - username: gbrown
#     oh_my_zsh:
#       theme: gentoo
#       plugins:
#         - git
#         - command-not-found
#         - aliases
#         - tmux
#       update_mode: auto
#       update_frequency: 13

# ironicbadger.docker_compose_generator
global_env_vars:
  - "TZ={{ ntp_timezone }}"
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
compose_schema_version: "3.8"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"

