ansible_become_password: "{{ secret_sudo }}"

ntp_timezone: America/New_York

do_become: True

# kgb_standard user setup internal role and oh-my-zsh
users:
  - username: gbrown
    groupname: gbrown
    home: yes
    uid: 1000
    gid: 1000
    password: "{{ secret_gbrown_pass }}"
    shell: /bin/zsh
    groups: adm,users,cdrom,sudo,dip,plugdev
    oh-my-zsh:
      theme: gentoo
      plugins:
        - git
        - command-not-found
        - aliases
        - tmux
      update_mode: auto
      update_frequency: 14
  - username: dockeruser
    groupname: users
    home: yes
    uid: 99
    password: "!"
    shell: /bin/bash

# grog.package
package_list:
  - zsh
  - curl
  - git
  - bash-completion
  - gnupg2
  - htop
  - jq
  - ncdu
  - neofetch
  - net-tools
  - python3
  - python3-apt
  - python3-pip
  - tmux
  - wget
  - mc
  - sudo
  - tree
  - iotop
  - iftop
