ansible_become_password: "{{ secret_sudo }}"

# geerlingguy.ntp
ntp_timezone: America/New_York


do_become: True

# kgb_standard user setup internal role and oh-my-zsh
# users:
#   - username: gbrown
#     groupname: gbrown
#     home: yes
#     uid: 1000
#     gid: 1000
#     password: "{{ secret_gbrown_pass }}"
#     shell: /bin/zsh
#     groups: adm,users,cdrom,sudo,dip,plugdev
#     oh-my-zsh:
#       theme: gentoo
#       plugins:
#         - git
#         - command-not-found
#         - aliases
#         - tmux
#       update_mode: auto
#       update_frequency: 14
#   - username: dockeruser
#     groupname: users
#     home: yes
#     uid: 99
#     password: "!"
#     shell: /bin/bash

# grog.package
package_list:
  - name: zsh
  - name: curl
  - name: git
  - name: bash-completion
  - name: gnupg2
  - name: htop
  - name: jq
  - name: ncdu
  - name: neofetch
  - name: net-tools
  - name: python3
  - name: python3-apt
  - name: python3-pip
  - name: tmux
  - name: wget
  - name: mc
  - name: sudo
  - name: tree
  - name: iotop
  - name: iftop

# grog user and group creation
group_list_group:
  - { name: gbrown, gid: 1000, state: present }

user_list_group:
  - name: gbrown
    uid: 1000
    group: gbrown
    groups:
      - adm
      - sudo
      - users
      - cdrom
      - dip
      - plugdev
    append: yes
    password: "{{ secret_gbrown_pass }}"
    move_home: yes
    shell: /bin/zsh
    comment: "Glenn Brown"
    state: present

# oh-my-zsh
users:
  - username: gbrown
    oh_my_zsh:
      theme: gentoo
      plugins:
        - git
        - command-not-found
        - aliases
        - tmux
      update_mode: auto
      update_frequency: 13
      