---
# some basic variables
main_username: gbrown
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# ironicbadger.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker compose -f ~/docker-compose.yml " }
  - { alias: "dcporph", command: "docker compose -f ~/docker-compose.yml --remove-orphans " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;" }
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop " }
  - { alias: "dir", command: "ls --color=auto --format=vertical" }
  - { alias: "egrep", command: "egrep --color=auto" }
  - { alias: "fgrep", command: "fgrep --color=auto" }
  - { alias: "grep", command: "grep --color=auto" }
  - { alias: "l", command: "ls -CF --color=auto" }
  - { alias: "la", command: "ls -A --color=auto" }
  - { alias: "ll", command: "ls -l --color=auto" }
  - { alias: "vdir", command: "ls --color=auto --format=long" }
  - { alias: "mc", command: "/usr/share/mc/bin/mc-wrapper.sh" }

# geerlingguy.ntp
ntp_timezone: America/New_York

# grog.package
package_update_cache: yes
package_list:
  - name: curl
  - name: dialog
  - name: git
  - name: bash-completion
  - name: gnupg2
  - name: gawk
  - name: htop
  - name: jq
  - name: ncdu
  - name: neofetch
  - name: net-tools
  - name: python3
  - name: python3-apt
  - name: python3-pip
  - name: pv
  - name: tmux
  - name: wget
  - name: mc
  - name: sudo
  - name: tree
  - name: iotop
  - name: iftop
  - name: zip
  - name: unzip
  - name: p7zip-full
  - name: rar
  - name: unrar

# grog.group
group_list:
  - { name: gbrown, gid: 1000, state: present }

# grog.user
user_list:
  - name: gbrown
    uid: 1000
    group: gbrown
    groups:
      - adm
      - sudo
      - users
      - cdrom
      - dip
      - plugdev
      - video
    append: yes
    password: "{{ secret_gbrown_pass }}"
    move_home: yes
    shell: /bin/bash
    comment: "Glenn Brown"
    state: present

# grog.authorized-key
authorized_key_list:
  - name: gbrown
    authorized_keys:
      - key: "{{ secret_gbrown_key }}"

# kgb-htop
htop_users:
  - homedir: "/home/gbrown"

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID=99
  - PGID=100
compose_schema_version: "3.8"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"

