---
# some basic variables
main_username: gbrown
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# ironicbadger.bash-aliases
bash_aliases:
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;" }
  - { alias: "dir", command: "ls --color=auto --format=vertical" }
  - { alias: "egrep", command: "egrep --color=auto" }
  - { alias: "fgrep", command: "fgrep --color=auto" }
  - { alias: "grep", command: "grep --color=auto" }
  - { alias: "l", command: "ls -CF --color=auto" }
  - { alias: "la", command: "ls -A --color=auto" }
  - { alias: "ll", command: "ls -l --color=auto" }
  - { alias: "vdir", command: "ls --color=auto --format=long" }
  - { alias: "mc", command: "/usr/share/mc/bin/mc-wrapper.sh" }

# geerlingguy.ntp
ntp_timezone: America/New_York

# grog.package
package_update_cache: true

# grog.authorized-key
authorized_key_list:
  - name: "{{ main_username }}"
    authorized_keys:
      - key: "{{ secret_gbrown_sshkey }}"
  - name: root
    authorized_keys:
      - key: "{{ secret_root_sshkey }}"

# geerlingguy.docker
docker_install_compose: false
docker_install_compose_plugin: true 
docker_users: 
  - "{{ main_username }}"

# kgb-htop
htop_users:
  - homedir: "/home/{{ main_username }}"

# prometheus.prometheus.node_exporter
node_exporter_textfile_dir: /var/lib/node-exporter
node_exporter_version: 1.7.0
node_exporter_system_group: prometheus
node_exporter_system_user: prometheus

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID=99
  - PGID=100
compose_schema_version: "3.8"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"
