---

# Default ssh port to use
ansible_ssh_port: "{{ cloud_ssh_port }}"

# geerlingguy.ntp
ntp_daemon: ntp
ntp_package: ntp
ntp_timezone: "America/New_York"

#Tailscale
tailscale_args: "--accept-routes"
tailscale_authkey: "{{ tailscale_oci_authkey }}"

bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker compose -f ~/docker-compose.yml " }
  - { alias: "dcporph", command: "docker compose -f ~/docker-compose.yml --remove-orphans " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop " }


# geerlingguy.security
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_ssh_port: "{{ cloud_ssh_port }}"
security_sudoers_passwordless:
 - "{{ main_username }}"

# traefik
#traefik_debug_log: true
traefik_enable_dashboard: true
traefik_docker_provider: true
traefik_insecure_transport: true
traefik_acme: true
traefik_domains: 
  - name: "{{ public_domain_1 }}"
    sans: "*.{{ public_domain_1 }}"
  - name: "{{ public_domain_2 }}"
    sans: "*.{{ public_domain_2 }}"

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID={{ main_uid }}
  - PGID={{ main_gid }}
appdata_path: "/home/{{ main_username }}/appdata"
container_config_path: /config

containers:
  ###
  - service_name: traefik
    active: true
    image: traefik:latest
    container_name: traefik:v2.11.0
    security_opt:
      - no-new-privileges:true
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - "{{ appdata_path }}/traefik:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.dashboard.rule=Host(`traefik.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.dashboard.entrypoints=websecure"'
      - '"traefik.http.routers.dashboard.service=api@internal"'
      - '"traefik.http.routers.dashboard.middlewares=auth"'
      - '"traefik.http.routers.dashboard.tls.certresolver=default"'
      - '"traefik.http.routers.dashboard.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.dashboard.tls.domains[0].sans=*.{{ public_domain_1 }}"'
      - '"traefik.http.middlewares.auth.basicauth.users={{ traefik_dashboard_auth }}"'
  ###
  - service_name: overseerr
    active: true
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - LOG_LEVEL=debug
    volumes:
      - "{{ appdata_path }}/overseerr:/app/config"
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.overseerr.rule=Host(`requests.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.overseerr.entrypoints=websecure"'
      - '"traefik.http.routers.overseerr.tls.certresolver=default"'
      - '"traekik.http.routers.overseerr.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traekik.http.routers.overseerr.tls.domains[0].sans=*.{{ public_domain_1 }}"'
  ###
  - service_name: freshrss
    active: true
    image: freshrss/freshrss:1.23.1-alpine
    container_name: freshrss
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - CRON_MIN=1,31
    volumes:
      - "{{ appdata_path }}/freshrss/data:/var/www/FreshRSS/data"
      - "{{ appdata_path }}/freshrss/extensions:/var/www/FreshRSS/extensions"
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.freshrss.rule=Host(`freshrss.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.freshrss.entrypoints=websecure"'
      - '"traefik.http.routers.freshrss.tls.certresolver=default"'
      - '"traefik.http.routers.freshrss.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.freshrss.tls.domains[0].sans=*.{{ public_domain_1 }}"'
