---

# Default ssh port to use
ansible_ssh_port: "{{ cloud_ssh_port }}"

# geerlingguy.ntp
ntp_daemon: ntp
ntp_package: ntp
ntp_timezone: "America/New_York"

#Tailscale
tailscale_args: "--accept-routes"

bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker compose -f ~/docker-compose.yml " }
  - { alias: "dcporph", command: "docker compose -f ~/docker-compose.yml --remove-orphans " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop " }


# geerlingguy.security
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_ssh_port: "{{ cloud_ssh_port }}"
security_sudoers_passwordless:
 - "{{ main_username }}"

# traefik
#traefik_debug_log: true
traefik_enable_dashboard: true
traefik_docker_provider: true
traefik_insecure_transport: true
traefik_domains: 
  - name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37313064363037626437636366366638623463373662376366323239356536343832623138643737
          6538656136626464346364343237626164313062386234390a383939346238646637376130623933
          63343666373461373563346131373732626639376132636266323035613933326166626432633731
          3034656534623730380a623865623864353438656632633632633636653133383933316436643961
          6266
  - name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323934343732636265653938383865373832346162346465336635636638623433653763633830
          6138633138663134393830636131623935643334356539660a633865343131616638633934323066
          63633039366230663861326130643938366232376665363538376639643737653731363662363563
          3363646364613662640a336663306437623331383734393538306636353037363430383432346663
          3865

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID={{ main_uid }}
  - PGID={{ main_gid }}
appdata_path: "/home/{{ main_username }}/appdata"
container_config_path: /config

containers:
  ###
  - service_name: traefik
    active: true
    image: traefik:latest
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_global_api_key }}"
    volumes:
      - "{{ appdata_path }}/traefik:/etc/traefik"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.dashboard.rule=Host(`traefik.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.dashboard.entrypoints=websecure"'
      - '"traefik.http.routers.dashboard.service=api@internal"'
      - '"traefik.http.routers.dashboard.middlewares=auth"'
      - '"traefik.http.routers.dashboard.tls.certresolver=default"'
      - '"traefik.http.routers.dashboard.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.dashboard.tls.domains[0].sans=*.{{ public_domain_1 }}"'
      - '"traefik.http.middlewares.auth.basicauth.users={{ traefik_dashboard_auth }}"'
  ###
  - service_name: overseerr
    active: true
    image: sctx/overseerr:latest
    container_name: overseerr
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - LOG_LEVEL=debug
    volumes:
      - "{{ appdata_path }}/overseerr:/app/config"
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.overseerr.rule=Host(`requests.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.overseerr.entrypoints=websecure"'
      - '"traefik.http.routers.overseerr.tls.certresolver=default"'
      - '"traekik.http.routers.overseerr.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traekik.http.routers.overseerr.tls.domains[0].sans=*.{{ public_domain_1 }}"'
  ###
  - service_name: freshrss
    active: true
    image: freshrss/freshrss:arm
    container_name: freshrss
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - CRON_MIN=1,31
    volumes:
      - "{{ appdata_path }}/freshrss/data:/var/www/FreshRSS/data"
      - "{{ appdata_path }}/freshrss/extensions:/var/www/FreshRSS/extensions"
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.freshrss.rule=Host(`freshrss.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.freshrss.entrypoints=websecure"'
      - '"traefik.http.routers.freshrss.tls.certresolver=default"'
      - '"traefik.http.routers.freshrss.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.freshrss.tls.domains[0].sans=*.{{ public_domain_1 }}"'
  ###
  - service_name: thelounge
    active: true
    image: thelounge/thelounge:latest
    container_name: thelounge
    user: "{{ main_uid }}:{{ main_gid }}"
    environment:
      - TZ={{ ntp_timezone }}
    volumes:
      - "{{ appdata_path }}/thelounge:/var/opt/thelounge"
    network_mode: bridge
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.thelounge.rule=Host(`thelounge.{{ public_domain_1 }}`)"'
      - '"traefik.http.routers.thelounge.entrypoints=websecure"'
      - '"traefik.http.routers.thelounge.tls.certresolver=default"'
      - '"traefik.http.routers.thelounge.tls.domains[0].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.thelounge.tls.domains[0].sans=*.{{ public_domain_1 }}"'
  ###
  - service_name: watchtower
    active: true
    image: containrrr/watchtower
    container_name: watchtower
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - WATCHTOWER_SCHEDULE=0 0 2 * * MON
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL={{ watchtower_email_alert }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
    restart: unless-stopped
