---
target_os: proxmox

# geerlingguy.ntp
ntp_daemon: chrony
ntp_package: chrony

# grog.package
package_list_group:
- name: lm-sensors
- name: nvme-cli
- name: wget
- name: smartmontools
- name: lshw
- name: dmidecode