---
hostname: heimdall

# geerlingguy.ntp
ntp_daemon: ntp
ntp_package: ntp

# Bash Aliases
bash_docker: true
bash_apt: true
bash_systemctl: true

# grog.package
# package_list_group:
# - name: lm-sensors
# - name: nvme-cli
# - name: wget
# - name: smartmontools
# - name: lshw
# - name: dmidecode

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID={{ main_uid }}
  - PGID={{ main_gid }}
appdata_path: "/home/{{ main_username }}/appdata"
container_config_path: /config
