---

target_os: debian #proxmox
hostname_odin: pvetest
main_username: gbrown

# geerlingguy.ntp
ntp_daemon: chrony
ntp_package: chrony

# grog.package
package_list_group:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: fio
  - name: git
  - name: hddtemp
  - name: htop
  - name: ffmpeg
  - name: iftop
  - name: intel-gpu-tools
  - name: iotop
  - name: ipmitool
  - name: lm-sensors
  - name: mc
  - name: mutt
  - name: ncdu
  - name: net-tools
  - name: nut
  - name: nut-client
  - name: nut-server
  - name: nfs-kernel-server
  - name: nmap
  - name: nvme-cli
  - name: openssh-server
  - name: python3
  - name: python3-apt
  - name: python-setuptools
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: xfsprogs
  - name: zfsutils-linux

# grog.group
group_list_group:
  - { name: kbrown, gid: 1001, state: present }

# grog.user
user_list_group:
  - name: kbrown
    uid: 1001
    group: kbrown
    groups:
      - users
    append: yes
    shell: /bin/false
    comment: "Kristen Brown"
    state: present
  - name: dockeruser
    uid: 99
    group: users
    shell: /bin/bash

# geerlingguy.docker
docker_install_compose: false
docker_install_compose_plugin: true 
docker_users: gbrown

# kgb-odin
# TODO: change secret to 1password lookup
odin_main_storage_path: /mnt/storage
extra_mountpoints:
  - { path: /mnt/nvme1tb, diskbyid: /dev/disk/by-id/ata-QEMU_HARDDISK_QM00011-part1, fs: ext4, opts: "defaults,discard" }
samba_users:
  - username: gbrown
    password: "{{ secret_samba_gbrown }}"
  - username: kbrown
    password: "{{ secret_samba_kbrown }}"

# ironicbadger.snapraid + kgb-odin
snapraid_runner: true
snapraid_install: true
snapraid_parity_disks:
  - { path: /mnt/parity1, diskbyid: /dev/disk/by-id/ata-QEMU_HARDDISK_QM00017-part1, fs: xfs, opts: defaults, content: false }

snapraid_data_disks:
  - { path: /mnt/disk1, diskbyid: /dev/disk/by-id/ata-QEMU_HARDDISK_QM00021-part1, fs: xfs, opts: defaults, content: true }
  - { path: /mnt/disk2, diskbyid: /dev/disk/by-id/ata-QEMU_HARDDISK_QM00023-part1, fs: xfs, opts: defaults, content: false }
  - { path: /mnt/disk3, diskbyid: /dev/disk/by-id/ata-QEMU_HARDDISK_QM00019-part1, fs: xfs, opts: defaults, content: false }

snapraid_config_excludes:
  - "*.unrecoverable"
  - "/tmp/"
  - "/lost+found/"
  - "downloads/"
  - "appdata/"
  - "*.!sync"
  - ".AppleDouble"
  - "._AppleDouble"
  - ".DS_Store"
  - "._.DS_Store"
  - ".Thumbs.db"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - ".AppleDB"
  - ".nfo"

# tigattack.mergerfs
mergerfs_install_mode: github_releases
mergerfs_version: 2.35.1
mergerfs_mounts:
  - path: /mnt/storage
    branches: 
      - /mnt/disk*
      - /mnt/nvme1tb
      - /mnt/tank/fuse
    options: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs"
  - path: /mnt/jbod
    branches:
      - /mnt/disk*
    options: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,dropcacheonclose=true,minfreespace=250G,fsname=jbod"

# geerlingguy.nfs
nfs_exports: [ "/mnt/storage    *(rw,sync,no_root_squash,fsid=25)" ]
  