---

# traefik
traefik_exposed_by_default: false
traefik_docker_provider: true
traefik_acme: true
traefik_acme_staging: true
traefik_domains:
  - name: "{{ local_domain }}"
    sans: "*.{{ local_domain }}"

# ironicbadger.docker_compose_generator
global_env_vars:
  - TZ={{ ntp_timezone }}
  - PUID={{ main_uid }}
  - PGID={{ main_gid }}
appdata_path: "/home/{{ main_username }}/appdata"
container_config_path: /config

container_networks:
  ###
  - network_name: traefik
    active: true
    external: true

containers:
  ###
  - service_name: traefik
    active: true
    image: traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    include_global_env_vars: false
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ appdata_path }}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "{{ appdata_path }}/traefik/acme.json:/etc/traefik/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
      - default
    extra_hosts:
      - '"host.docker.internal:172.17.0.1"'
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.traefik.rule=Host(`traefik-dashboard.{{ local_domain }}`)"'
      - '"traefik.http.routers.traefik.entrypoints=web"'
      - '"traefik.http.middlewares.traefik-auth.basicauth.users={{ traefik_dashboard_auth }}"'
      - '"traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"'
      - '"traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"'
      - '"traefik.http.routers.traefik.middlewares=traefik-https-redirect"'
      - '"traefik.http.routers.traefik-secure.entrypoints=websecure"'
      - '"traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.{{ local_domain }}`)"'
      - '"traefik.http.routers.traefik-secure.middlewares=traefik-auth"'
      - '"traefik.http.routers.traefik-secure.tls=true"'
      - '"traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"'
      - '"traefik.http.routers.traefik-secure.tls.domains[0].main={{ local_domain }}"'
      - '"traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ local_domain }}"'
      - '"traefik.http.routers.traefik-secure.tls.domains[1].main={{ public_domain_1 }}"'
      - '"traefik.http.routers.traefik-secure.tls.domains[1].sans=*.{{ public_domain_1 }}"'
      - '"traefik.http.routers.traefik-secure.tls.domains[2].main={{ public_domain_2 }}"'
      - '"traefik.http.routers.traefik-secure.tls.domains[2].sans=*.{{ public_domain_2 }}"'
      - '"traefik.http.routers.traefik-secure.service=api@internal"'
  ###
  - service_name: nginxhello
    active: true
    image: nginxdemos/nginx-hello
    container_name: nginxhello
    include_global_env_vars: false
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.nginxhello.rule=Host(`nginxhello.{{ local_domain }}`)"'
      - '"traefik.http.routers.nginxhello.entrypoints=websecure"'
      - '"traefik.http.routers.nginxhello.tls=true"'
      - '"traefik.http.routers.nginxhello.tls.certresolver=cloudflare"'
      - '"traefik.http.routers.nginxhello.tls.domains[0].main={{ local_domain }}"'
      - '"traefik.http.routers.nginxhello.tls.domains[0].sans=*.{{ local_domain }}"'
      - '"traefik.http.services.nginxhello.loadbalancer.server.port=8080"'

  - service_name: whoami
    active: true
    image: traefik/whoami
    container_name: whoami
    include_global_env_vars: false
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.whoami.rule=Host(`whoami.{{ local_domain }}`)"'
      - '"traefik.http.routers.whoami.entrypoints=websecure"'
      - '"traefik.http.routers.whoami.tls=true"'
      - '"traefik.http.routers.whoami.tls.domains[0].main={{ local_domain }}"'
      - '"traefik.http.routers.whoami.tls.domains[0].sans=*.{{ local_domain }}"'
      - '"traefik.http.routers.whoami.tls.certresolver=cloudflare"'
      
  - service_name: nginxtest
    active: true
    image: lscr.io/linuxserver/nginx
    container_name: nginxtest
    include_global_env_vars: false
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      - '"traefik.enable=true"'
      - '"traefik.http.routers.nginxtest.rule=Host(`nginxtest.{{ local_domain }}`)"'
      - '"traefik.http.routers.nginxtest.entrypoints=websecure"'
      - '"traefik.http.routers.nginxtest.tls=true"'
      - '"traefik.http.routers.nginxtest.tls.domains[0].main={{ local_domain }}"'
      - '"traefik.http.routers.nginxtest.tls.domains[0].sans=*.{{ local_domain }}"'
      - '"traefik.http.routers.nginxtest.tls.certresolver=cloudflare"'
      