---

- name: basic preflight duplicate checks
  block:
  # source: https://www.reddit.com/r/ansible/comments/b5tzp1/ansible_get_list_of_subelements_and_assert_for/
    - name: create data structure to check via assertion
      ansible.builtin.set_fact:
        dupe_check: |
          {
            'reservation_count_total': {{ openwrt_dhcp_static_leases | length }},
            'reservation_mac_unique': {{ (openwrt_dhcp_static_leases | selectattr('mac', 'defined') | map(attribute='mac') | list) | unique | length }},
            'reservation_ip_unique': {{ (openwrt_dhcp_static_leases | selectattr('ip', 'defined') | map(attribute='ip') | list) | unique | length }},
            'reservation_hostname_unique': {{ (openwrt_dhcp_static_leases | selectattr('hostname', 'defined') | map(attribute='hostname') | list) | unique | length }}
          }

    - name: print counts for basic duplicate checks
      debug:
        var: dupe_check
      
    - name: assert no duplicates
      assert:
        that:
        - dupe_check.reservation_count_total == dupe_check.reservation_mac_unique
        - dupe_check.reservation_count_total == dupe_check.reservation_ip_unique
        - dupe_check.reservation_count_total == dupe_check.reservation_ip_unique
    
  rescue:
    - name: dupe check
      debug:
        msg: "Duplicate entry: {{ item | duplicates }}"
      loop:
        - "{{ openwrt_dhcp_static_leases | selectattr('mac', 'defined') | map(attribute='mac') }}"
        - "{{ openwrt_dhcp_static_leases | selectattr('ip', 'defined') | map(attribute='ip') }}"
        - "{{ openwrt_dhcp_static_leases | selectattr('hostname', 'defined') | map(attribute='hostname') }}"

    - name: Fail when errors
      fail:
        msg: 'Duplicate mac address, ip address or hostname found. Go to fail!'