---

- name: Checking for existing installation
  stat: 
    path: "{{ vuetorrent_install_location }}/vuetorrent/version.txt"
  register: vuetorrent_install_check

- name: Read current version file
  slurp:
    src: "{{ vuetorrent_install_location }}/vuetorrent/version.txt"
  register: package_version
  when: vuetorrent_install_check.stat.exists

- name: Extract current version
  set_fact: 
    current_vuetorrent_version: "{{ package_version.content }}"
  when: vuetorrent_install_check.stat.exists

- name: Check if we need to install
  set_fact:
    force_install: "{{ vuetorrent_force_install == true or vuetorrent_install_check.stat.exists == false }}"

- name: Get latest release
  uri:
    url: https://api.github.com/repos/VueTorrent/VueTorrent/releases/latest
    url_username: "{{ github_api_user | default (omit) }}"
    url_password: "{{ github_api_pass | default (omit) }}"
    return_content: true
    force_basic_auth: "{{ github_api_auth | default (omit) }}"
  register: release_latest
  when: vuetorrent_version is undefined and force_install == true

- name: Set version if not already defined
  set_fact:
    vuetorrent_version: "{{ release_latest.json.tag_name }}"
  when: vuetorrent_version is undefined and force_install == true

- name: Download release
  when: force_install == true
  get_url:
    url: https://github.com/VueTorrent/VueTorrent/releases/download/{{ vuetorrent_version }}/vuetorrent.zip
    dest: /tmp

- block:
    - name: Create install directory
      file:
        path: "{{ vuetorrent_install_location }}/vuetorrent"
        state: directory
        owner: dockeruser
        group: users
        mode: 0755
    
    - name: Install VueTorrent
      unarchive:
        src: /tmp/vuetorrent.zip
        dest: "{{ vuetorrent_install_location }}"
        remote_src: true
        owner: dockeruser
        group: users
  when: force_install == true
        