---
- name: restart smartmon timer
  listen: restart collectors
  ansible.builtin.systemd:
    name: node-exporter-smartmon.timer
    daemon_reload: true
    state: restarted

- name: restart nvme metrics timer
  listen: restart collectors
  ansible.builtin.systemd:
    name: node-exporter-nvme.timer
    daemon_reload: true
    state: restarted

- name: restart apt info timer
  listen: restart collectors
  ansible.builtin.systemd:
    name: node-exporter-apt.timer
    daemon_reload: true
    state: restarted
