---
###############################################################################
# dnsmasq package list
###############################################################################

dnsmasq_default_packages_apt:
  - ca-certificates
  - curl
  - dialog
  - lsof
  - python3
  - python3-apt
  - sudo
  - sqlite3
  - unzip
  - wget
  - dnsmasq
  - dnsmasq-base
  - dnsmasq-utils

###############################################################################
# dnsmasq role defaults
###############################################################################

dnsmasq_config_dir: /etc/dnsmasq.d
dnsmasq_interface: '{{ ansible_default_ipv4.interface }}'
dnsmasq_query_logging: true
dnsmasq_cache_size: 10000
dnsmasq_dns_fqdn_required: true
dnsmasq_listening: local
dnsmasq_dnssec: true
#dnsmasq_rev_server_cidr: ''
#dnsmasq_rev_server_target: ''
dnsmasq_dns1: '1.1.1.1'
dnsmasq_dns2: '1.0.0.1'
dnsmasq_dhcp_active: 'false'
dnsmasq_dhcp_start: ''
dnsmasq_dhcp_end: ''
dnsmasq_dhcp_router: ''
dnsmasq_dhcp_leasetime: '24h'
dnsmasq_domain: 'home'
dnsmasq_dhcp_ipv6: false 
dnsmasq_dhcp_rapid_commit: false
