---

- name: Install snapd
  ansible.builtin.apt:
    name: "{{ apt_required_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install snap core
  community.general.snap:
    name:
      - core

- name: Install Oracle Cloud Agent
  community.general.snap:
    name: oracle-cloud-agent
    classic: true

