---

- name: check if ssl cert file is there
  ansible.builtin.stat:
    path: "{{ znc_ssl_certfile }}"
  register: znc_sslcert_status

- name: ensure znc config directory exists
  ansible.builtin.file:
    path: "{{ znc_config_root }}/configs"
    state: directory
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    mode: 0700

# Create self signed cert
- name: create self signed cert
  ansible.builtin.command: docker run --rm --user "{{ main_uid }}:{{ main_gid }}" -v {{ znc_config_root }}:/znc-data znc:slim --makepem
  args:
    creates: "{{ znc_config_root }}/znc.pem"
  become: true
  become_user: "{{ znc_user }}"
  when: not znc_sslcert_status.stat.exists
  
- name: copy znc configuration file
  ansible.builtin.template:
    src: znc.conf.j2
    dest: "{{ znc_config_root }}/configs/znc.conf"
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    mode: 0600

- name: ensure znc modules directory exists
  ansible.builtin.file:
    path: "{{ znc_config_root }}/modules"
    state: directory
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    mode: 0700

- name: git clone znc-clientbuffer module
  ansible.builtin.git:
    repo: "{{ znc_clientbuffer_repo }}"
    dest: /usr/local/src/znc-clientbuffer
    version: master

- name: git clone znc-palaver module
  ansible.builtin.git:
    repo: "{{ znc_palaver_repo }}"
    dest: /usr/local/src/znc-palaver
    version: master

- name: git clone znc-logsearch module
  ansible.builtin.git:
    repo: "{{ znc_logsearch_repo }}"
    dest: /usr/local/src/znc-logsearch
    version: master

- name: copy znc-clientbuffer module into znc modules directory
  ansible.builtin.copy:
    src: /usr/local/src/znc-clientbuffer/clientbuffer.cpp
    dest: "{{ znc_config_root }}/modules"
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    remote_src: true

- name: copy znc-palaver module into znc modules directory
  ansible.builtin.copy:
    src: /usr/local/src/znc-palaver/palaver.cpp
    dest: "{{ znc_config_root }}/modules"
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    remote_src: true

- name: copy znc-logsearch module into znc modules directory
  ansible.builtin.copy:
    src: /usr/local/src/znc-logsearch/logsearch.py
    dest: "{{ znc_config_root }}/modules"
    owner: "{{ znc_user }}"
    group: "{{ znc_group }}"
    remote_src: true
