---
- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: "{{ ga_package_name }}"

- name: Start and enable service on reboot
  ansible.builtin.systemd_service:
    name: "{{ ga_service_name }}"
    daemon_reload: true
    enabled: true
    state: started