---
me:
  username: gbrown
  uid: 501
  gid: 20
  home: /Users/gbrown
  name: 'Glenn Brown'
  key: "{{ secret_gbrown_sshkey }}"

# Dotfiles
dotfiles_repo: 'https://github.com/glennbrown/dotfiles.git'
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bashrc
  - .bash_profile
  - .config/starship.toml
  - .config/ghostty
  - .inputrc
  - .vimrc
  - .zshrc
  - .zshenv
  - .zprofile

# Beszel Agent
beszel_agent_sshkey: "{{ odin_agent_key }}"
beszel_agent_token: "{{ odin_agent_token }}"

# Certbot Configuration
certbot_install_method: 'package'
certbot_hsts: true
certbot_certs:
  - domains:
      - "{{ local_domain }}"
      - "*.{{ local_domain }}"