---

# Sudo Password for Become
ansible_become_password: "{{ lookup('community.general.onepassword', 'Ansible Become', field='password') }}"

# SSH Keys
secret_gbrown_sshkey: "{{ lookup('community.general.onepassword', 'Personal ed25519 Key', field='public key') }}"
secret_root_sshkey: "{{ lookup('community.general.onepassword', 'root - ed25519', field='public key') }}"
    
# Cable Modem secret used for motorola exporter
modem_secret: "{{ lookup('community.general.onepassword', 'MB8600', field='password') }}"

# Cloudflare
cloudflare_account_email: "{{ lookup('community.general.onepassword', 'Cloudflare', field='username') }}"
cloudflare_account_id: "{{ lookup('community.general.onepassword', 'Cloudflare', field='account_id') }}"
cloudflare_global_api_key: "{{ lookup('community.general.onepassword', 'Cloudflare', field='global_api_key') }}"
cloudflare_caddy_api_token: "{{ lookup('community.general.onepassword', 'Cloudflare', field='caddy_api_token') }}"
cloudflare_acme_api_token: "{{ lookup('community.general.onepassword', 'Cloudflare', field='acmesh_api_token') }}"

# znc
znc_gbrown_hash: "{{ lookup('community.general.onepassword', 'Znc', field='Hash') }}"
znc_gbrown_salt: "{{ lookup('community.general.onepassword', 'Znc', field='Salt') }}"

#Tailscale
tailscale_authkey: "{{ lookup('community.general.onepassword', 'Tailscale', field='Tailscale Auth Key') }}"
