---

- name: Create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: dockeruser
    group: users
    mode: 0777
  with_items: 
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"

- name: Mount disks
  mount:
    name: "{{ item.path }}"
    src: "{{ item.diskbyid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: mounted
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/storage'

- name: Set ZFS ARC size
  copy:
    src: etc/modprobe.d/zfs.conf
    dest: /etc/modprobe.d/zfs.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - update initramfs