---
#
###############################################################################
# Setup main server odin
###############################################################################
#

- name: odin - ensure hostname is set correctly
  hostname:
    name: "{{ hostname_odin }}"
  
- name: odin - disk setup
  include_tasks: disks.yml

- name: odin - file sharing
  include_tasks: file_sharing.yml

- name: odin - tools install
  include_tasks: tools.yml

- name: odin - setup lm_sensors
  include_tasks: sensors.yml
  
  