---
#
###############################################################################
# Install lm_sensors and configure it
###############################################################################
#

- name: sensors | ensure lm_sensors is installed
  ansible.builtin.apt:
    name: lm-sensors
    update_cache: true
    state: present
  
- name: sensors | apply nct6775 grub fix
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=""$'
    line: 'GRUB_CMDLINE_LINUX="acpi_enforce_resources=lax"'
  notify: update grub

# loading drivetemp module
- name: sensors | load drivetemp module
  community.general.modprobe: 
    name: drivetemp
    state: present
    persistent:  present

# loading nct6775 module
- name: sensors | load nct6775 module
  community.general.modprobe:
    name: nct6775
    state: present
    persistent: present