services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:2.8.2
    container_name: smokeping
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.username }}
      - PGID={{ me.username }}
    volumes:
      - ~/.config/smokeping:/config
      - ~/.local/share/smokeping/data:/data
    ports:
      - 8080:80
    restart: unless-stopped