---
###############################################################################
# Dnsmasq Install
###############################################################################
# Lightweight DNS and DHCP Server
#

- name: install dnsmasq
  ansible.builtin.apt:
    name: "{{ dnsmasq_default_packages_apt }}"
    state: present
    update_cache: true
  register: dnsmasq_install

- name: enable dnsmasq on boot
  ansible.builtin.systemd:
    name: dnsmasq.service
    enabled: true
    daemon-reload: true

- name: enable logrotate for dnsmasq logs
  ansible.builtin.copy:
    src: logrotate-dnsmasq
    dest: /etc/logrotate.d/dnsmasq

- name: touch custom hosts file
  ansible.builtin.file:
    path: /etc/hosts.custom
    state: touch
  when: dnsmasq_install.changed
  