---

# Replace stock debian config, but create a backup!
- name: write dnsmasq conf file
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    backup: yes
  notify: restart dnsmasq

# Write DNS Config (mostly borrowed from pihole)
- name: write dnsmasq dns config
  ansible.builtin.template:
    src: dnsmasq-base.conf.j2
    dest: "{{ dnsmasq_config_dir }}/01-dnsmasq-base.conf"
  notify: restart dnsmasq

# Write DHCP Configuration File
- name: write pihole dhcp configuration file
  ansible.builtin.template:
    src: dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/02-dnsmasq-dhcp.conf"
  notify: restart dnsmasq

# Write DNS Records
- name: write dns file
  ansible.builtin.template:
    src: dns-overrides.conf.j2
    dest: "{{ dnsmasq_config_dir }}/03-dns-overrides.conf"
  notify: restart dnsmasq

# Write Static DHCP Reservations
- name: write static dhcp file
  ansible.builtin.template:
    src: static-dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/04-static-dhcp.conf"
  register: dhcp_changed

# RFC671 config, taken from pihole
- name: copy rfc6761 config file
  ansible.builtin.copy:
    src: 06-rfc6761.conf
    dest: "{{ dnsmasq_config_dir }}/06-rfc6761.conf"
  notify: restart dnsmasq

# Pointer DNS Records
- name: write reverse dns file
  ansible.builtin.template:
    src: reverse-lookup.conf.j2
    dest: "{{ dnsmasq_config_dir }}/07-reverse-lookup.conf"
  notify: restart dnsmasq

# Revoke DHCP Leases when dhcp has changed.
- block:
    - name: revoke existing leases | remove file
      ansible.builtin.file:
        path: "/var/lib/misc/dnsmasq.leases"
        state: absent

    - name: revoke existing leases | create new file
      ansible.builtin.file:
        path: "/var/lib/misc/dnsmasq.leases"
        state: touch
  when: dhcp_changed.changed
  notify: restart dnsmasq