---

- name: Install pip dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-venv
    - python3-pip
    - virtualenv

- name: Install certbot via pip
  pip:
    name:
      - certbot
      - certbot-dns-cloudflare
    virtualenv: "{{ certbot_dir }}"
    state: present

- name: Symlink certbot into place.
  file:
    src: "{{ certbot_dir }}/bin/certbot"
    dest: /usr/local/bin/certbot
    state: link
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: '/usr/local/bin/certbot'
