services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.3
    container_name: sabnzbd
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.uid }}
    volumes:
      - {{ appdata_path }}/sabnzbd:/config
      - {{ scratch_path }}/downloads:/downloads
    ports:
      - 8080:8080
    restart: always
  