services:
    
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: {{ ansible_hostname }}
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - {{ appdata_path }}/plexmediaserver:/config
      - media:{{ media_path }}:ro
    environment:
      - TZ={{ ntp_timezone }}
      - PLEX_CLAIM={{ plex_claim_token }}
      - PLEX_UID={{ me.uid }}
      - PLEX_GID={{ me.uid }}
    tmpfs:
      - /transcode:mode=0777
    restart: always

volumes:
  media:
    name: media
    driver: local
    driver_opts:
      type: cifs
      o: username={{ me.username }},password={{ secret_synology_gbrown }},uid=0,gid=100,dir_mode=0777,file_mode=0666
      device: //yggdrasil/Media