---

- name: install znc
  ansible.builtin.include_tasks: install.yml

- name: configure znc
  ansible.builtin.include_tasks: config.yml

- name: clients
  ansible.builtin.include_tasks: clients.yml
    
    