---
###############################################################################
# Pi-Hole Install
###############################################################################
# DNS blackhole.
#

- name: install | create pihole group
  ansible.builtin.group:
    name: pihole
    gid: 998
    state: present

- name: install | create pihole user
  ansible.builtin.user:
    name: pihole
    uid: 998
    group: pihole
    create_home: false
    home: /home/pihole
    shell: /usr/sbin/nologin
    state: present

- name: install | install pihole dependencies
  ansible.builtin.apt:
    name: "{{ pihole_default_packages_apt }}"
    state: latest
    update_cache: true
  
- name: install | create "{{ pihole_config_dir }}"
  ansible.builtin.file:
    path: "{{ pihole_config_dir }}"
    mode: 0775
    owner: pihole
    group: pihole
    state: directory

- name: install | set deployment config
  ansible.builtin.template:
    src: pihole-setupVars.conf.j2
    dest: "{{ pihole_config_dir }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644

- name: install | set binary location
  ansible.builtin.stat:
    path: /usr/local/bin/pihole
  register: pihole_binary

- name: install | determine if pihole is already installed
  ansible.builtin.set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists|default(false) }}"

- name: install | fetching latest installer
  ansible.builtin.get_url:
    url: 'https://install.pi-hole.net'
    dest: '/tmp/pihole-install.sh'
    mode: 0755
  notify: start pihole-FTL
  when: not pihole_installed

- name: install | run installer
  ansible.builtin.command: '/tmp/pihole-install.sh --unattended'
  notify: start pihole-FTL
  when: not pihole_installed

- name: postinstall | auto-redirect to admin page
  ansible.builtin.include_tasks: lighttpd.yml