---

# DNS overrides will create wildcard records technically speaking the dns custom file is not needed but has
# the added benefit of providing PTR record support with needing to write a standalong reverse lookup file. 
- name: Write pihole dns custom file
  ansible.builtin.template:
    src: custom.list.j2
    dest: "{{ pihole_config_dir }}/custom.list"
  notify: restart pihole dns

- name: Write dns overrides file
  ansible.builtin.template:
    src: dns-overrides.conf.j2
    dest: "{{ dnsmasq_config_dir }}/03-dns-overrides.conf"
  notify: restart pihole dns

# This file will be created by install but we need write it again incase we update DHCP config
- name: Write pihole dhcp configuration file
  ansible.builtin.template:
    src: pihole-dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/02-pihole-dhcp.conf"
  notify: restart pihole dns

- name: Write static dhcp file
  ansible.builtin.template:
    src: static-dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/04-pihole-static-dhcp.conf"
  register: dhcp_changed

- name: Write cnames file
  ansible.builtin.template:
    src: cnames.conf.j2
    dest: "{{ dnsmasq_config_dir }}/05-pihole-custom-cname.conf"
  notify: restart pihole dns  

- block:
    - name: DHCP has changed, remove existing leases file
      ansible.builtin.file:
        path: "{{ pihole_config_dir }}/dhcp.leases"
        owner: pihole
        group: pihole
        state: absent

    - name: DHCP has changed, re-create leases file
      ansible.builtin.file:
        path: "{{ pihole_config_dir }}/dhcp.leases"
        owner: pihole
        group: pihole
        state: touch
  when: dhcp_changed.changed
  notify: restart pihole dns