---

- name: pihole-updatelists | check if already installed
  ansible.builtin.stat:
    path: /usr/local/sbin/pihole-updatelists
  register: pihole_updatelists_binary

- name: pihole-updatelists | copy updatelist conf file
  ansible.builtin.copy:
    src: pihole-updatelists.conf
    dest: /etc/pihole-updatelists.conf
    mode: 0644
    owner: root
    group: root
  register: pihole_updatelists_conf
  notify: reload pihole-updatelists

- name: pihole-updatelists | create directory for custom whitelists
  ansible.builtin.file:
    path: "{{ whitelists_config_dir }}"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: pihole-updatelists | copy whitelists
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ whitelists_config_dir }}/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ role_path }}/files/pihole*whitelist.txt"
  notify: reload pihole-updatelists

- block:

    - name: pihole-updatelists | fetch latest installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh
        dest: /tmp/pihole-updatelist-install.sh
        mode: 0755    
    
    - name: pihole-updatelists | run installer
      ansible.builtin.command: '/tmp/pihole-updatelist-install.sh'
      register: pihole_updatelists_install
      changed_when: "'Reloading systemd manager' in pihole_updatelists_install.stdout"
      notify: reload pihole-updatelists
      
  when: not pihole_updatelists_binary.stat.exists
