services:
  traefik:
    image: traefik:v3.2.3
    container_name: traefik
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /etc/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
      - /etc/traefik/config.d:/etc/traefik/config.d:ro
      - /etc/traefik/acme.json:/etc/traefik/acme.json
      - /var/log/traefik:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 46697:46697
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik-dashboard.{{ public_domain_1 }}`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/etc/traefik/.htpasswd
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.{{ public_domain_1 }}`)
      - traefik.http.routers.traefik-secure.middlewares=traefik-auth
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main={{ public_domain_1 }}
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ public_domain_1 }}
      - traefik.http.routers.traefik-secure.tls.domains[1].main={{ public_domain_1 }}
      - traefik.http.routers.traefik-secure.tls.domains[1].sans=*.{{ public_domain_1 }}
      - traefik.http.routers.traefik-secure.service=api@internal