---

- name: Install python3-passlib
  package:
    name: python3-passlib

- name: Ensure config directories exist
  file:
    dest: "{{ traefik_data_path }}/{{ item }}"
    state: directory
  loop:
    - config
    - letsencrypt
    - log

- name: Copy traefik tls config file
  template:
    src: tls-config.yml.j2
    dest: "{{ traefik_data_path }}/config/tls-config.yml"

- name: Create Dashboard users
  community.general.htpasswd:
    path: "{{ traefik_data_path }}/.htpasswd"
    name: kgbadmin
    password: "{{ traefik_dashboard_password }}"

- name: Copy logrotate config
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/traefik
  when: traefik_log_rotate == true
