services:
  kms:
    image: ghcr.io/py-kms-organization/py-kms:latest-next
    container_name: kms
    hostname: kms
    environment:
      - TZ=America/New_York
    volumes:
      - ~/.local/share/py-kms/db:/home/py-kms/db
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1688:1688
    restart: unless-stopped