services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:2.9.0
    container_name: smokeping
    hostname: smokeping
    environment:
      TZ: {{ ntp_timezone }}
      PUID: {{ me.uid }}
      PGID: {{ me.gid }}
    volumes:
      - {{ appdata_path }}/smokeping/config:/config
      - {{ appdata_path }}/smokeping/data:/data
    ports:
      - 8289:80
    restart: always

volumes:
  media:
    name: media
    driver: local
    driver_opts:
      type: cifs
      o: username={{ me.username }},password={{ secret_synology_gbrown }},uid=0,gid=0,dir_mode=0777,file_mode=0666
      device: //192.168.10.20/Media
      