---

- name: Download Diffie-Hellman Parameters
  get_url:
    url: "{{ dhparams_pem_download }}"
    dest: "{{ nginx_config_dir }}/dhparams.pem"
    mode: 0440
  become: true

- name: Ensure config directories exist
  file:
    path: "{{ nginx_config_dir }}"
    state: directory
    mode: 0755
  loop:
    - sites-enabled
    - streams-enabled
    - conf.d
  become: true

- name: Check if we already backed up stock config
  stat:
    path: "{{ nginx_config_dir }}/nginx.conf.orig"
  register: debian_stock_config
  become: true

- name: Copy Debian stock config
  copy:
    src: "{{ nginx_config_dir }}/nginx.conf"
    dest: "{{ nginx_config_dir }}/nginx.conf.orig"
    remote_src: true
  when: not debian_stock_config.stat.exists
  become: true

- name: Install nginx base config
  copy:
    src: nginx.conf
    dest: "{{ nginx_config_dir }}/nginx.conf"
    mode: 0644
  become: true
  notify: reload nginx

- name: Copy proxy parameters
  copy:
    src: proxy_params
    dest: "{{ nginx_config_dir }}/proxy_params"
    mode: 0644
  become: true
  notify: reload nginx

- name: Copy additional config files
  template:
    src: "{{ item }}"
    dest: "{{ nginx_config_dir }}/conf.d/{{ item | basename }}"
    mode: 0644
  loop:
    - conf.d/docker-resolver.conf
    - conf.d/ssl.conf
  become: true
  notify: reload nginx

- name: Disable default site
  file:
    path: "{{ nginx_config_dir }}/sites-enabled/default"
    state: absent
  become: true
  notify: reload nginx

- name: Install HTTPS Redirect
  copy:
    src: nginx-https-redirect.conf
    dest: "{{ nginx_config_dir }}/sites-enabled/nginx-https-redirect.conf"
    mode: 0644
  become: true
  notify: reload nginx

- name: Copy nginx config for docker proxied sites
  template:
    src: nginx-docker.conf.j2
    dest: "{{ nginx_config_dir }}/sites-enabled/{{ item.filename | default(item.server_name.split(' ')[0] ~ '.conf') }}"
    mode: 0644
  become: true
  notify: reload nginx
  loop: "{{ nginx_docker_sites }}"
  when: nginx_docker_sites is defined

- name: Copy nginx config for proxied sites
  template:
    src: nginx-proxy.conf.j2
    dest: "{{ nginx_config_dir }}/sites-enabled/{{ item.filename | default(item.server_name.split(' ')[0] ~ '.conf') }}"
    mode: 0644
  become: true
  notify: reload nginx
  loop: "{{ nginx_proxy_sites }}"
  when: nginx_proxy_sites is defined