---
# Create config dirs
- name: Create config directories
  file:
    path: ~/{{ item }}
    state: directory
  become: true
  become_user: "{{ main_username }}"
  loop:
    - .config
    - .local/share
   