---

# Package manager will install certbot as part of its dependency chain, but for posterity we will use Geerlings role task
- block:

  - name: Install certbot from package manager
    include_role:
      name: geerlingguy.certbot
      tasks_from: install-with-package.yml
      vars_from: default.yml

  - name: Install certbot-dns-cloudflare from package manager
    package:
      name: python3-certbot-dns-cloudflare
      state: present

  when: certbot_install_method == 'package'

- block:

  - name: Install certbot from snap
    include_role:
      name: geerlingguy.certbot
      tasks_from: install-with-snap.yml
    
  - name: Make sure certbot trust plugins with root
    command: snap set certbot trust-plugin-with-root=ok
    register: snap_set_plugin_trust_root
    changed_when: "snap_set_plugin_trust_root is failed"

  - name: Install certbot-dns-cloudflare from snap
    snap:
      name: certbot-dns-cloudflare

  when: certbot_install_method == 'snap'

- name: Create certbot folder
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0755
  
- name: Copy certbot config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'templates/confcloudflare.ini.j2', dest: '/etc/letsencrypt/dnscloudflare.ini' }
    - { src: 'templates/letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini' }

- include_role:
    name: geerlingguy.certbot
    tasks_from: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
  loop_control:
    loop_var: cert_item