---

- name: Create config directories
  file:
    path: "/home/{{ main_username }}/{{ item }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - 'appdata/hass'
    - scripts

# we use Seabios/i440fx VM's not needed from cloud-image
- name: Remove efi boot volume
  mount:
    path: /boot/efi
    state: absent

- name: Add additional SSH Keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
  loop:
    - name: root
      key: "{{ secret_root_sshkey }}"
  
- name: Set root users password
  user:
    name: root
    password: "{{ secret_root_pass }}"
    password_lock: false
    update_password: always

