---

# Replace stock debian config, but create a backup!
- name: Write dnsmasq conf file
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

# Write DNS Config (mostly borrowed from pihole)
- name: Write dnsmasq base config
  ansible.builtin.template:
    src: dnsmasq-base.conf.j2
    dest: "{{ dnsmasq_config_dir }}/01-dnsmasq-base.conf"
  notify: restart dnsmasq

# Write DHCP Configuration File
- name: Write DHCP configuration file
  ansible.builtin.template:
    src: dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/02-dnsmasq-dhcp.conf"
  notify: restart dnsmasq
  when: dnsmasq_dhcp_active | bool

# Write DNS Records
- name: Write DNS Overrides file
  ansible.builtin.template:
    src: dns-overrides.conf.j2
    dest: "{{ dnsmasq_config_dir }}/03-dns-overrides.conf"
  notify: restart dnsmasq
  when: dnsmasq_dns_overrides is defined

# Write Static DHCP Reservations
- name: Write static dhcp file
  ansible.builtin.template:
    src: static-dhcp.conf.j2
    dest: "{{ dnsmasq_config_dir }}/04-static-dhcp.conf"
  register: dhcp_changed
  when: dnsmasq_dhcp_reservations is defined

# RFC671 config, taken from pihole
- name: Copy rfc6761 config file
  ansible.builtin.copy:
    src: 06-rfc6761.conf
    dest: "{{ dnsmasq_config_dir }}/06-rfc6761.conf"
  notify: restart dnsmasq

# DNS A Records
- name: Write DNS A Records file
  ansible.builtin.template:
    src: host-records.conf.j2
    dest: "{{ dnsmasq_config_dir }}/07-host-records.conf"
  notify: restart dnsmasq
  when: dnsmasq_dns_records is defined

# Pointer DNS Records
- name: Write Reverse DNS file
  ansible.builtin.template:
    src: reverse-lookup.conf.j2
    dest: "{{ dnsmasq_config_dir }}/08-reverse-lookup.conf"
  notify: restart dnsmasq
  when: "'dnsmasq_dhcp_reservations' is defined or 'dnsmasq_dns_records' is defined"

# DNS CNAME's
- name: Write DNS cname file
  ansible.builtin.template:
    src: cnames.conf.j2
    dest: "{{ dnsmasq_config_dir }}/09-dns-cnames.conf"
  notify: restart dnsmasq
  when: dnsmasq_dns_cnames is defined

# Revoke DHCP Leases when dhcp has changed.
- block:
    - name: revoke existing leases | remove file
      ansible.builtin.file:
        path: "/var/lib/misc/dnsmasq.leases"
        state: absent

    - name: revoke existing leases | create new file
      ansible.builtin.file:
        path: "/var/lib/misc/dnsmasq.leases"
        state: touch
  when: dhcp_changed.changed
  notify: restart dnsmasq