---

# Basic Server setup
- name: Basic server setup
  hosts: all
  tags: [setup, init]
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  
  pre_tasks:
    - name: Change hostname
      ansible.builtin.hostname:
        name: "{{ set_hostname }}"
      notify:
        - Hostname has changed
      when: set_hostname is defined
    - block:
        - name: Disable proxmox enterprise repo
          replace:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            regexp: '^deb https://enterprise\.proxmox\.com/debian/pve bookworm pve-enterprise'
            replace: '#deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
          notify: Update apt cache
        - name: Disable proxmox enterprise ceph repo
          replace:
            path: /etc/apt/sources.list.d/ceph.list
            regexp: '^deb https://enterprise\.proxmox\.com/debian/ceph-quincy bookworm enterprise'
            replace: '#deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
          notify: Update apt cache
        - name: Switch to proxmox community repo
          apt_repository:
            filename: /etc/apt/sources.list.d/pve-no-subscription
            repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
            state: present
          notify: Update apt cache
      when: "'proxmox' in group_names"
    
  roles:
    - role: grog.group
    - role: grog.user
    - role: grog.authorized-key
    - role: proxmox_nag_removal
      when: "'proxmox' in group_names"
    - role: apt-mirror
      when: ansible_os_family == 'Debian'
    - role: grog.package
    - role: geerlingguy.ntp
    - role: geerlingguy.docker
      when: "'docker' in group_names"
      tags: docker

  handlers:
    - name: Update hosts file
      listen: Hostname has changed
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: '^127.0.0.1 localhost$'
        line: '{{ ansible_default_ipv4.address }} {{ set_hostname }}.{{ local_domain }} {{ set_hostname }}'
        owner: root
        group: root
        mode: 0644
    - name: Reboot
      listen: Hostname has changed
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible due to hostname change
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 2
        post_reboot_delay: 30
        test_command: uptime
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

# Configure primary server
- name: Configure odin
  hosts: odin
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  roles:
    - role: htop
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: odin
      tags: tools, disks, file-sharing
    - role: tigattack.mergerfs
    - role: ironicbadger.snapraid
    - role: geerlingguy.nfs
    - role: prometheus.prometheus.node_exporter
      tags: prom
    - role: node_exporter_collectors
      tags: prom
    - role: traefik
      tags: compose
    - role: ironicbadger.docker_compose_generator
      tags: compose

# Configure caddy
#- name: Configure caddy
#  hosts: caddy
#  
#  vars_files:
#    - 'vars/vault.yml'
#    - 'vars/secrets_lookup.yml'
#  
#  roles:
#    - role: ironicbadger.bash_aliases
#    - role: ironicbadger.figurine
#    - role: caddy
#      tags: caddy

# Configure thor     
- name: Configure thor
  hosts: thor
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  roles:
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine

# Configure Loki
#- name: Configure loki
#  hosts: loki
#  vars_files:
#    - 'vars/vault.yml'
#    - 'vars/secrets_lookup.yml'
#  roles:

# Debian Testing Server
- name: Debian Testing Server
  hosts: test
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  roles:
#    #- role: traefik
#    #  tags: compose
#    - role: coredns_docker_proxy
#      tags: compose
#    - role: ironicbadger.docker_compose_generator
#      tags: compose

- name: Configure celtic
  hosts: celtic
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  roles:
    - role: geerlingguy.security
    - role: artis3n.tailscale
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: ocagent
    - role: traefik
      tags: compose
    - role: ironicbadger.docker_compose_generator
      tags: compose

- name: Configure DNS Servers
  hosts: dns
  vars_files:
    - 'vars/vault.yml'
    - 'vars/secrets_lookup.yml'
  roles:
    - role: ironicbadger.figurine
    - role: ironicbadger.bash_aliases
    - role: dnsmasq
      tags: dns