---

# Basic Server setup
- name: Basic server setup
  hosts: all
  tags: [setup, init]
  vars_files:
    - 'vars/vault.yml'
  
  pre_tasks:
    - name: Change hostname
      ansible.builtin.hostname:
        name: "{{ set_hostname }}"
      notify:
        - Hostname has changed
      when: set_hostname is defined

  roles:
    - role: grog.group
    - role: grog.user
    - role: grog.authorized-key
    - role: apt-mirror
      when: ansible_os_family == 'Debian'
    - role: grog.package
      tags: packages
    - role: geerlingguy.ntp
  
  handlers:
    - name: Update hosts file
      listen: Hostname has changed
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: '^127.0.0.1 localhost$'
        line: '{{ ansible_default_ipv4.address }} {{ set_hostname }}.{{ local_domain }} {{ set_hostname }}'
        owner: root
        group: root
        mode: 0644
    - name: Reboot
      listen: Hostname has changed
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible due to hostname change
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 2
        post_reboot_delay: 30
        test_command: uptime
        
# Install Docker on hosts
- name: Install Docker
  hosts: docker
  tags: [init, docker]
  vars_files:
    'vars/vault.yml'
  roles:
    - role: geerlingguy.docker

# Configure primary server
# Proxmox
- name: Configure odin
  hosts: odin
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: ironicbadger.proxmox_nag_removal
    - role: htop
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: odin
      tags: tools, disks, file-sharing
    - role: tigattack.mergerfs
    - role: ironicbadger.snapraid
    - role: geerlingguy.nfs
    - role: prometheus.prometheus.node_exporter
      tags: prom
    - role: custom_prometheus
      tags: prom
    - role: traefik
      tags: compose
    - role: ironicbadger.docker_compose_generator
      tags: compose
  
# Configure pihole
# Debian
- name: Configure pihole dns
  hosts: pihole
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: htop
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    #- role: nickjj.acme_sh
    #  tags: ssl
    #- role: pihole-dhcp-dns
    #  tags: dns, dhcp, pihole

# Configure hodur (dhcp/dns)
# Debian
- name: "Configure hodur (dhcp/dns server)"
  hosts: hodur
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: ironicbadger.bash_aliases
    - role: dnsmasq
      tags: [dhcp, dns]

# Configure caddy
# Debian
- name: Configure caddy
  hosts: caddy
  vars_files:
    - 'vars/vault.yml' 
  roles:
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: caddy
      tags: caddy

# Configure thor
# Debian        
- name: Configure thor
  hosts: thor
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    #- role: znc
    #  tags: znc
    #- role: nickjj.acme_sh
    #  tags: znc, ssl

# Configure Loki
#- name: Configure loki
#  hosts: loki
#  vars_files:
#    - 'vars/vault.yml'
#  roles:

- name: Configure cloud server
  hosts: cloud
  vars_files:
    'vars/vault.yml'
  roles:
    - role: geerlingguy.security
    - role: artis3n.tailscale
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: ocagent


