---
  # Basic setup for all servers
  - name: Server Inital Setup
    hosts: all
    vars_files:
      - 'vars/vault.yml'
    become: "{{ do_become }}"
    roles:
      - role: grog.package
      - role: grog.group
      - role: grog.user
      - role: gantsign.oh-my-zsh
      
  # Configure Proxmox main test
  - name: Configure odin 
    hosts: pvetest
    vars_files:
      - 'vars/vault.yml'
    roles:
      - { role: ironicbadger.proxmox_nag_removal, become: yes }
      
