---

  # Configure primary server
  # Proxmox
  - name: Configure odin
    hosts: odin
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: ironicbadger.proxmox_nag_removal
      - role: htop
      - role: apt-mirror
        tags: packages
      - role: grog.package
        tags: packages
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: odin
        tags: tools, disks, file-sharing
      - role: tigattack.mergerfs
      - role: ironicbadger.snapraid
      - role: geerlingguy.nfs
      - role: prometheus.prometheus.node_exporter
        tags: prom
      - role: custom_prometheus
        tags: prom
      - role: traefik
        tags: compose
      - role: ironicbadger.docker_compose_generator
        tags: compose
  
  # Configure pihole
  # Debian
  # - name: Configure pihole dns
  #   hosts: pihole
  #   vars_files:
  #     - 'vars/vault.yml'
  #   roles:
  #     - role: grog.group
  #     - role: grog.user
  #     - role: grog.authorized-key
  #     - role: apt-mirror
  #       tags: packages
  #     - role: grog.package
  #       tags: packages
  #     - role: htop
  #     - role: geerlingguy.ntp
  #     - role: ironicbadger.bash_aliases
  #     - role: nickjj.acme_sh
  #       tags: ssl
  #     - role: pihole-dhcp-dns
  #       tags: dns, dhcp, pihole

  # Configure hodur (dhcp/dns)
  # Debian
  - name: "Configure hodur (dhcp/dns server)"
    hosts: hodur
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: apt-mirror
        tag: packages
      - role: grog.package
        tags: packages
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: dnsmasq
        tags: dhcp, dns

  # Configure caddy
  # Debian
  - name: Configure caddy server
    hosts: caddy
    vars_files:
      - 'vars/vault.yml' 
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: apt-mirror
        tags: packages
      - role: grog.package
        tags: packages
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: caddy
        tags: caddy

  # Configure thor
  # Debian        
  - name: Configure thor
    hosts: thor
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: apt-mirror
        tags: packages, apt
      - role: grog.package
        tags: packages
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: znc
        tags: znc
      - role: nickjj.acme_sh
        tags: znc, ssl

  # Configure Loki
  - name: Configure loki
    hosts: loki
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: geerlingguy.ntp
