---

  # Configure Media Server
  - name: Configure server odin
    hosts: pvetest
    vars_files:
      - 'vars/vault.yml'
    #become: "{{ do_become }}"
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: kgb-htop
      - role: ironicbadger.proxmox_nag_removal
      - role: grog.package
      - role: gantsign.oh-my-zsh
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: kgb-apt 
      - role: kgb-odin
      - role: tigattack.mergerfs
      - role: ironicbadger.snapraid
      - role: geerlingguy.nfs
