---

  # Configure Media Server
  - name: configure server odin
    hosts: pvetest
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: kgb-htop
      - role: ironicbadger.proxmox_nag_removal
      - role: kgb-apt-mirror
      - role: grog.package
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: kgb-odin
      - role: tigattack.mergerfs
      - role: ironicbadger.snapraid
      - role: geerlingguy.nfs
      - role: prometheus.prometheus.node_exporter
        tags: prom
      - role: kgb-prom
        tags: prom
      - role: ironicbadger.docker_compose_generator
        tags: compose
        
