---

  # Configure primary server
  # Proxmox
  - name: configure odin
    hosts: odin
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: ironicbadger.proxmox_nag_removal
      - role: kgb-htop
      - role: kgb-apt-mirror
        tags: packages
      - role: grog.package
        tags: packages
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.figurine
      - role: kgb-odin
        tags: tools, disks, file-sharing
      - role: tigattack.mergerfs
      - role: ironicbadger.snapraid
      - role: geerlingguy.nfs
      - role: prometheus.prometheus.node_exporter
        tags: prom
      - role: kgb-prom
        tags: prom
      - role: kgb-traefik
        tags: compose
      - role: ironicbadger.docker_compose_generator
        tags: compose
  
  # Configure heimdall (Topton unit)
  # Proxmox
  - name: configure heimdall
    hosts: heimdall
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: ironicbadger.proxmox_nag_removal
      - role: kgb-apt-mirror
        tags: packages
      - role: grog.package
        tags: packages
      - role: kgb-htop
      - role: geerlingguy.docker
      - role: geerlingguy.ntp
      - role: kgb-heimdall
      - role: ironicbadger.figurine
      - role: ironicbadger.bash_aliases
      - role: prometheus.prometheus.node_exporter
        tags: prom
      - role: kgb-prom
        tags: prom
      #- role: kgb-traefik
      #  tags: compose
      #- role: ironicbadger.docker_compose_generator
      #  tags: compose

  # Configure pihole
  # Debian
  - name: configure pihole dns
    hosts: pihole
    vars_files:
      - 'vars/vault.yml'
    roles:
      - role: grog.group
      - role: grog.user
      - role: grog.authorized-key
      - role: kgb-apt-mirror
        tags: packages
      - role: grog.package
        tags: packages
      - role: kgb-htop
      - role: geerlingguy.ntp
      - role: ironicbadger.bash_aliases
      - role: kgb-dhcp-dns
        tags: dns, dhcp, pihole
        
