services:
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.36.3
    container_name: prowlarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/sonarr:/config
      - /mnt/scratch/downloads:/downloads
      - /mnt/storage/Media/TV Shows:/tv
    ports:
      - 8989:8989
    depends_on:
      - sabnzbd
      - qbittorrent
      - prowlarr
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.25.0
    container_name: radarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/radarr:/config
      - /mnt/scratch/downloads:/downloads
      - /mnt/storage/Media/Movies:/movies
    ports:
      - 7878:7878
    depends_on:
      - sabnzbd
      - prowlarr
      - qbittorrent
    restart: unless-stopped
