services:
  tautulli:
    image: tautulli/tautulli:v2.15.1
    container_name: tautulli
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/tautulli:/config
    ports:
      - 8181:8181
    depends_on:
      - plex
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.32.2
    container_name: prowlarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/Sonarr:/config
      - /srv/scratch/downloads:/downloads
      - tv-shows:/tv
    ports:
      - 8989:8989
    depends_on:
      - sabnzbd
      - qbittorrent
      - prowlarr
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:5.22.4
    container_name: radarr
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/Radarr:/config
      - /srv/scratch/downloads:/downloads
      - movies:/movies
    ports:
      - 7878:7878
    depends_on:
      - sabnzbd
      - prowlarr
      - qbittorrent
    restart: unless-stopped

volumes:
  tv-shows:
    name: tv-shows
    driver: local
    driver_opts:
      type: cifs
      o: username={{ me.username }},password={{ secret_synology_gbrown }},uid=0,gid=100,dir_mode=0777,file_mode=0666
      device: //yggdrasil/Media/TV Shows
  movies:
    name: movies
    driver: local
    driver_opts:
      type: cifs
      o: username={{ me.username }},password={{ secret_synology_gbrown }},uid=99,gid=100,dir_mode=0777,file_mode=0666
      device: //yggdrasil/Media/Movies