---
# Paths
appdata_path: '/mnt/appdata'
media_path: '/mnt/media'
scratch_path: '/mnt/scratch'

# grog.package
package_list_host:
  - name: fio
  - name: mediainfo

# Drive mounts
automount_drives: true
drive_mounts:
  - mountpoint: '/mnt/scratch'
    device: '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-part1'
    fstype: ext4
    options:
      - defaults
  - mountpoint: /mnt/media
    device: "//yggdrasil/Media"
    fstype: cifs
    options:
      - 'user={{ me.username }}'
      - 'password={{ secret_synology_gbrown }}'
      - 'uid=0'
      - 'gid=100'
      - 'dir_mode=0777'
      - 'file_mode=0666'