---

# Default ssh port to use
ansible_ssh_port: "{{ cloud_ssh_port }}"

# apt-mirror
apt_source_mode: modern

# Bash Aliases
bash_docker: true
bash_apt: true
bash_systemctl: true

# geerlingguy.ntp
ntp_daemon: ntp
ntp_package: ntp
ntp_timezone: "America/New_York"

#Tailscale
tailscale_args: "--accept-routes"
tailscale_authkey: "{{ tailscale_oci_authkey }}"

# geerlingguy.security
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_ssh_port: "{{ cloud_ssh_port }}"
security_sudoers_passwordless:
 - "{{ main_username }}"

# firewall rules
ufw:
  - comment: 'SSH VPS Port'
    rule: 'allow'
    port: '{{ cloud_ssh_port }}'
    proto: 'any'
    route: 'no'
  - comment: 'HTTP Traffic'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'HTTPS Traffic'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'IRC Bouncer'
    rule: 'allow'
    port: '46697'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'

# traefik
#traefik_debug_log: true
traefik_acme: true
traefik_cloudflare_proxy: true
traefik_extra_entrypoints:
  - name: irc
    port: '46697'

# certbot
certbot_install_method: snap
certbot_admin_email: "{{ cloudflare_account_email }}"
certbot_cloudlare_api_token: "{{ cloudflare_certbot_api_token }}"
certbot_certs:
  - domains:
      - "{{ public_domain_1 }}"
      - "*.{{ public_domain_1 }}"
  - domains:
      - "{{ public_domain_2 }}"
      - "*.{{ public_domain_2 }}"
    
# ZNC
znc_user: "{{ main_username }}"
znc_group: "{{ main_groupname }}"
znc_config_root: "/home/{{ main_username }}/.znc"

# ironicbadger.docker_compose_generator
appdata_path: '~/appdata'