---

# Default ssh port to use
ansible_ssh_port: "{{ cloud_ssh_port }}"
    
# apt-mirror
apt_source_mode: modern

package_list_host:
  - name: acl
  - name: goaccess

# NTP
ntp_timezone: "America/New_York"

# geerlingguy.security
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_ssh_port: "{{ cloud_ssh_port }}"
security_sudoers_passwordless:
 - "{{ me.username }}"

# firewall rules
ufw_firewall_rules:
  - comment: 'SSH VPS Port'
    rule: 'allow'
    port: '{{ cloud_ssh_port }}'
    proto: 'any'
    route: 'no'
  - comment: 'HTTP Traffic'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'HTTPS Traffic'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'

# certbot
certbot_install_method: snap
certbot_certs:
  - domains:
      - "{{ public_domain_1 }}"
      - "*.{{ public_domain_1 }}"
  - domains:
      - "{{ public_domain_2 }}"
      - "*.{{ public_domain_2 }}"

nginx_vhosts:
  - listen: "443 ssl default_server http2"
    server_name: "www.{{ public_domain_2 }}"
    server_redirect:
      - "{{ public_domain_2 }}"
      - "blog.{{ public_domain_2 }}"
    error_log: "/var/log/nginx/ghost.error.log"
    access_log: "/var/log/nginx/ghost.access.log main"
    state: present
    filename: ghost.conf
    extra_parameters: |
      set $upstream http://127.0.0.1:2368;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/{{ public_domain_2 }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ public_domain_2 }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ public_domain_2 }}/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "share.{{ public_domain_2 }}"
    error_log: "/var/log/nginx/gokapi.error.log"
    access_log: "/var/log/nginx/gokapi.access.log main"
    state: present
    filename: gokapi.conf
    extra_parameters: |
      set $upstream http://127.0.0.1:53842;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/{{ public_domain_2 }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ public_domain_2 }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ public_domain_2 }}/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "freshrss.{{ public_domain_1 }}"
    error_log: "/var/log/nginx/freshrss.error.log"
    access_log: "/var/log/nginx/freshrss.access.log main"
    state: present
    filename: freshrss.conf
    extra_parameters: |
      set $upstream http://127.0.0.1:8081;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/{{ public_domain_1 }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ public_domain_1 }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ public_domain_1 }}/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "ntfy.{{ public_domain_1 }}"
    error_log: "/var/log/nginx/ntfy.error.log"
    access_log: "/var/log/nginx/ntfy.access.log main"
    state: present
    filename: ntfy.conf
    extra_parameters: |
      set $upstream http://127.0.0.1:8080;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/{{ public_domain_1 }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ public_domain_1 }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ public_domain_1 }}/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
