---

# Bash Aliases
bash_docker: true
bash_apt: true
bash_systemctl: true

package_list_host:
  - name: intel-gpu-tools
  - name: nvtop
  - name: ffmpeg
  - name: fuse-overlayfs
  - name: cifs-utils

network_mountpoints:
  - path: /mnt/media
    id: //yggdrasil/Media
    fs: cifs
    state: mounted
    opts: "user={{ me.username }},password={{ secret_synology_gbrown }},uid=0,gid=100,dir_mode=0777,file_mode=0666,_netdev"