---
# Paths
appdata_path: '/mnt/appdata'
media_path: '/mnt/media'
scratch_path: '/mnt/scratch'

# Traefik
traefik_data_path: '/etc/traefik'

# grog.package
package_list_host:
  - name: ffmpeg
  - name: fio
  - name: flac
  - name: golang
  - name: handbrake-cli
  - name: imagemagick
  - name: intel-gpu-tools
  - name: iperf3
  - name: lame
  - name: mediainfo
  - name: nvtop
  - name: snapper
  - name: socat
  - name: webp
  - name: x264
  - name: x265
  - name: yt-dlp

# Drive mounts
automount_drives: true
drive_mounts:
  - mountpoint: /mnt/media
    device: "//yggdrasil/Media"
    fstype: cifs
    options:
      - 'user={{ me.username }}'
      - 'password={{ secret_synology_gbrown }}'
      - 'uid=0'
      - 'gid=100'
      - 'dir_mode=0777'
      - 'file_mode=0666'
      - '_netdev'