---

homebrew_user: gbrown
homebrew_group: admin

homebrew_installed_packages:
  - name: bash
  - name: bash-completion@2
  - name: bbrew
  - name: brew-cask-completion
  - name: btop
  - name: bun
  - name: cdrtools
  - name: coreutils
  - name: cpio
  - name: cpufetch
  - name: diceware
  - name: diffutils
  - name: fastfetch
  - name: figurine
  - name: findutils
  - name: fio
  - name: ffmpeg
  - name: flac
  - name: gawk
  - name: gcc
  - name: gh
  - name: gnu-sed
  - name: gnu-tar
  - name: go
  - name: htop
  - name: imagemagick
  - name: inxi
  - name: iperf3
  - name: jq
  - name: just
  - name: lame
  - name: lesspipe
  - name: lz4
  - name: lzo
  - name: macmon
  - name: mactop
  - name: media-info
  - name: nano
  - name: nanorc
  - name: ncurses
  - name: neofetch
  - name: nmap
  - name: perl
  - name: pipx
  - name: pv
  - name: qemu
  - name: ruby
  - name: screenresolution
  - name: smartmontools
  - name: snappy
  - name: socat
  - name: sqlite
  - name: sshpass
  - name: svt-av1
  - name: teamookla/speedtest/speedtest
  - name: tmux
  - name: usbutils
  - name: webp
  - name: wget
  - name: when
  - name: x264
  - name: x265
  - name: xvid
  - name: xz
  - name: yt-dlp
  - name: zsh-autosuggestions
  - name: zsh-completions # Install upsteam head version
    state: head
  - name: zsh-history-substring-search
  - name: zstd
  # Rust Tools
  - name: diffr # Modern Unix `diff`
  - name: difftastic # Modern Unix `diff`
  - name: dua-cli # Modern Unix `du`
  - name: dust # Modern du
  - name: fzf # Fuzzy finder
  - name: fd # Find replacement
  - name: duf # Modern Unix `df`
  - name: entr # Modern Unix `watch`
  - name: eza # Moder `ls` replacement
  - name: procs # Modern replacement for ps
  - name: ripgrep # Modern grep replacement
  - name: starship # Prompt bling
  - name: tealdeer # Rust re-write of tldr which are community based manpages
  - name: uutils-coreutils # Rust rewrite of coreutils
  - name: uutils-diffutils # Rust rewrite of diffutils
  - name: uutils-findutils #Rust rewrite of findutils
  - name: zoxide # Modern cd replacment

homebrew_cask_apps:
  - name: bbedit
  - name: docker-desktop
  - name: font-jetbrains-mono
  - name: font-jetbrains-mono-nerd-font
  - name: font-meslo-lg-nerd-font
  - name: ghostty
  - name: google-chrome
  - name: grandperspective
  - name: hazel
  - name: jump-desktop-connect
  - name: plex-media-server
  - name: prowlarr
  - name: qbittorrent
  - name: radarr
  - name: raycast
  - name: sabnzbd
  - name: sonarr
  - name: the-unarchiver
  - name: timemachineeditor
  - name: utm
  - name: visual-studio-code

homebrew_taps:
  - glennbrown/tap
  - homebrew/cask-fonts
  - homebrew/command-not-found
  - homebrew/services
  - oven-sh/bun
  - teamookla/speedtest
  - valkyrie00/bbrew

# Dotfiles
configure_dotfiles: true
dotfiles_repo: git@github.com:glennbrown/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bashrc
  - .bash_profile
  - .config/starship.toml
  - .config/ghostty
  - .inputrc
  - .macos_defaults
  - .vimrc
  - .zshrc
  - .zshenv
  - .zprofile

configure_dock: true

dockitems_remove:
  - TV
  - 'App Store'
  - 'System Settings'
  - Freeform
  - News
  - Maps
  - Facetime
  - Calendar
  - Contacts

dockitems_persist:

mas_installed_apps:
  # Safari Extensions
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 1662217862, name: "Wipr" }
  # Media
  - { id: 510620098, name: "MediaInfo" }
  # Development
  - { id: 497799835, name: "Xcode" }
  # Tools
  - { id: 1168254295, name: "AmorphousDiskMark" }
  - { id: 1474276998, name: "HP Smart" }
  - { id: 1492174677, name: "Text Case" }
