---
# Paths
appdata_path: '/mnt/appdata'
media_path: '/mnt/media'
scratch_path: '/mnt/nvme1/scratch'

docker_compose_generator_output_mode: 'stack'
docker_compose_generator_output_path: '/srv/docker'

# Traefik
traefik_data_path: '/etc/traefik'

# grog.package
package_list_host:
  - ffmpeg
  - fio
  - flac
  - golang
  - handbrake-cli
  - imagemagick
  - intel-gpu-tools
  - iperf3
  - lame
  - mediainfo
  - nvtop
  - socat
  - webp
  - x264
  - x265
  - yt-dlp

# Drive mounts
#automount_drives: true
#drive_mounts:
#  - mountpoint: /mnt/nvme1
#    device: /dev/disk/by-id/nvme-WDBRPG0010BNC-WRSN_21500K802847-part1
#    fstype: btrfs
#    options:
#      - 'discard'
#      - 'compress=zstd:3'
#      - 'defaults'
#  - mountpoint: /mnt/media
#    device: "//yggdrasil/Media"
#    fstype: cifs
#    options:
#      - 'user={{ me.username }}'
#      - 'password={{ secret_synology_gbrown }}'
#      - 'uid=0'
#      - 'gid=100'
#      - 'dir_mode=0777'
#      - 'file_mode=0666'
#      - '_netdev'