---
# Load kernel modules
kernel_modules:
  - name: drivetemp
  - name: nct6775

# Disable HA (only currently have a single node)
proxmox_disable_ha_services: true

# Paths
appdata_path: "/mnt/appdata"
media_path: "/mnt/media"
scratch_path: "/mnt/nvme1/scratch"

# docker_compose_generator_output_path: '/srv/docker'

# Traefik
traefik_data_path: "/etc/traefik"

# Packages
package_list_host:
  - ffmpeg
  - fio
  - flac
  - intel-gpu-tools
  - intel-microcode
  - golang
  - handbrake-cli
  - imagemagick
  - iperf3
  - lame
  - mediainfo
  - nvme-cli
  - nvtop
  - smartmontools
  - socat
  - webp
  - x264
  - x265
  - yt-dlp

# Drive mounts
automount_drives: true
drive_mounts:
  - mountpoint: /mnt/data
    device: "//yggdrasil/mediastack"
    fstype: cifs
    options:
      - "user={{ me.username }}"
      - "password={{ secret_synology_gbrown }}"
      - "uid=0"
      - "gid=100"
      - "dir_mode=0777"
      - "file_mode=0666"
      - "serverino"
      - "_netdev"
