---
# Certbot Configuration
certbot_install_method: 'snap'
certbot_hsts: true
certbot_certs:
  - domains:
      - "{{ local_domain }}"
      - "*.{{ local_domain }}"

#Nginx Configuration
nginx_hsts_redirect: true
nginx_remove_default_vhost: true

# Nginx Virtual Hosts
nginx_vhosts:
  - server_name: "sonarr.{{ local_domain }}"
    state: present
    filename: sonarr.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:8989;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "radarr.{{ local_domain }}"
    state: present
    filename: radarr.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:7878;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "prowlarr.{{ local_domain }}"
    state: present
    filename: prowlarr.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:9696;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "sabnzb.{{ local_domain }}"
    state: present
    filename: sabnzb.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:8080;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "qbittorrent.{{ local_domain }}"
    state: present
    filename: qbittorrent.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:8088;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "tautulli.{{ local_domain }}"
    state: present
    filename: tautulli.conf
    extra_parameters: |
      set $upstream http://192.168.10.12:8181;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "speedtest.{{ local_domain }}"
    state: present
    filename: speedtest.conf
    extra_parameters: |
      set $upstream http://192.168.10.14:8080;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "smokeping.{{ local_domain }}"
    state: present
    filename: smokeping.conf
    extra_parameters: |
      set $upstream http://192.168.10.15:8080;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "changedetection.{{ local_domain }}"
    state: present
    filename: changedetection.conf
    extra_parameters: |
      set $upstream http://192.168.10.14:5000;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;
  - server_name: "beszel.{{ local_domain }}"
    state: present
    filename: beszel.conf
    extra_parameters: |
      set $upstream http://192.168.10.15:8090;
      location / {
        proxy_pass $upstream;
      }
      ssl_certificate /etc/letsencrypt/live/home.ikgb.me/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/home.ikgb.me/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/home.ikgb.me/chain.pem;
      add_header Strict-Transport-Security "max-age=63072000" always;