---
# apt-mirror
apt_source_mode: modern

# Bash Aliases
bash_apt: true
bash_systemctl: true

package_list_host:
  - name: acl
  - name: goaccess

certbot_install_method: snap
certbot_certs:
  - domains: 
      - '*.{{ local_domain }}'

nginx_sites_config: "{{ lookup('template', 'roles/thor/templates/sites.conf.j2') }}"