---
- name: User Account Setup
  ansible.builtin.include_tasks:
    file: user.yml

- name: SSH Setup
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Kernel Module Setup
  ansible.builtin.include_tasks:
    file: modules.yml

- name: Ghostty Terminfo configuration
  ansible.builtin.include_tasks:
    file: ghostty.yml
