---

- name: Install Base Packages for Debian based
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - apt-file
    - aptitude
    - bash-completion
    - bc
    - bind9-dnsutils
    - command-not-found
    - curl
    - dialog
    - htop
    - gawk
    - git
    - gnupg2
    - htop
    - iotop
    - iftop
    - inxi
    - jq
    - mc
    - nano
    - net-tools
    - pv
    - python3
    - python3-apt
    - python3-pip
    - python3-setuptools
    - p7zip-full
    - p7zip-rar
    - screen
    - sudo
    - tmux
    - tree
    - wget
    - vim
    - unzip
    - zip
  when: ansible_os_family == 'Debian'

- name: Install Base Packages for Redhat based
  dnf:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - bash-completion
    - bc
    - bind-utils
    - curl
    - dialog
    - htop
    - epel-release
    - gawk
    - git
    - gnupg2
    - htop
    - iotop
    - iftop
    - inxi
    - jq
    - mc
    - nano
    - net-tools
    - PackageKit-command-not-found
    - pv
    - python3
    - python3-apt
    - python3-pip
    - python3-setuptools
    - p7zip
    - p7zip-plugins
    - screen
    - sudo
    - tmux
    - tree
    - wget
    - vim-enhanced
    - unzip
    - zip
  when: ansible_os_family == 'Redhat'