---
# MacOS ships with OpenSSH
- name: Install OpenSSH server
  ansible.builtin.package:
    name: "{{ openssh_package }}"
    state: present
  when: ansible_facts.system == 'Linux'

# Turning off deprecation warnings for module
# Fix has been proposed, will monitor https://github.com/ansible-collections/ansible.posix/pull/690
- name: Setup personal ssh public key
  ansible.posix.authorized_key:
    user: "{{ me.username }}"
    state: present
    key: "{{ me.key }}"

- name: Setup root ssh public_key
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ ssh_publickey_root }}"
  when: ansible_facts.system != 'Darwin'

- name: Enable SSH
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: yes
  when: ansible_facts.system != 'Darwin'
