---

- name: Install OpenSSH
  package:
    name: openssh-server

- name: Setup authorized keys
  authorized_key:
    user: "{{ me.username }}"
    key: "{{ me.key }}"
    state: present

- name: Setup root authorized key
  authorized_key:
    user: root
    key: "{{ secret_root_sshkey }}"
    
- name: Setup Service
  systemd_service:
    name: ssh
    daemon-reload: true
    enabled: true
    