- name: Create group
  group:
    name: "{{ me.username }}"
    gid: "{{ me.uid }}"

- name: Create user account
  user:
    name: "{{ me.username }}"
    uid: "{{ me.uid }}"
    group: "{{ me.username }}"
    home: "{{ me.home }}"
    comment: "{{ me.name }}"
    shell: /bin/bash
    password: "{{ secret_gbrown_pass }}"
    system: true
    update_password: on_create
    append: true
    groups: adm,sudo,users,cdrom,dip,plugdev,video  
  when: ansible_os_family == 'Debian'