---

- name: Install python3-passlib
  package:
    name: python3-passlib
    
- name: Create Docker network
  docker_network:
    name: traefik

- name: Ensure config directories exist
  file:
    dest: "{{ traefik_config_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - config.d

- name: Ensure log directories exist
  file:
    dest: "{{ traefik_log_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check if acme file exists already
  stat:
    path: "{{ traefik_config_path }}/acme.json"
  register: acme_json_file

- name: Ensure acme file exists
  file:
    dest: "{{ traefik_config_path }}/acme.json"
    state: touch
    owner: root
    group: root
    mode: 0600
  when: not acme_json_file.stat.exists

- name: Copy traefik config file from template
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_config_path }}/traefik.yml"
    owner: root
    group: root
    mode: 0644

- name: Copy traefik tls config file
  template:
    src: tls-config.yml.j2
    dest: "{{ traefik_config_path }}/config.d/tls-config.yml"
    owner: root
    group: root
    mode: 0644

- name: Copy traefik file provider rules
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ traefik_config_path }}/config.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ traefik_file_providers }}"
  when: traefik_file_providers is defined

- name: Create Dashboard users
  community.general.htpasswd:
    path: "{{ traefik_config_path }}/.htpasswd"
    name: kgbadmin
    password: "{{ traefik_dashboard_password }}"
    