---

- name: caddy | download latest release with cloudflare plugin
  ansible.builtin.get_url:
    url: "{{ caddy_amd64_linux_binary }}"
    dest: /usr/local/bin/caddy
    owner: root
    group: root
    mode: 0755

- name: caddy | create caddy user and group
  ansible.builtin.user:
    name: caddy
    group: caddy
