services:
  traefik:
    image: traefik
    container_name: traefik
    environment:
      - TZ={{ ntp_timezone }}
      - CF_DNS_API_TOKEN={{ cloudflare_traefik_api_token }}
    volumes:
      - {{ appdata_path }}/traefik/config:/config
      - {{ appdata_path }}/traefik/letsencrypt:/letsencrypt
      - {{ appdata_path }}/traefik/log:/log
      - {{ appdata_path }}/traefik/.htpasswd:/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=info
      - --api.insecure=false
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/config
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloud.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    extra_hosts:
      - host.docker.internal:172.17.0.1
    security_opt:
      - no-new-privileges:true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.o.{{ local_domain }}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/.htpasswd"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.o.{{ local_domain }}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=o.{{ local_domain }}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.o.{{ local_domain }}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
