services:
  plex:
    image: plexinc/pms-docker:1.41.7.9799-5bce000f7
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/appdata/plexmediaserver:/config
      - tv-shows:/tv:ro
      - movies:/movies:ro
    environment:
      - TZ={{ ntp_timezone }}
      - PLEX_CLAIM={{ plex_claim_token }}
      - PLEX_UID={{ me.uid }}
      - PLEX_GID=100
    tmpfs:
      - /transcode:mode=0777
    restart: unless-stopped
  
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    user: {{ me.uid }}:100
    group_add:
      - 104 #render
      - 44 #video
    hostname: us-ny-amh-jf
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/appdata/jellyfin/config:/config
      - /srv/appdata/jellyfin/cache:/cache
      - media:/media:ro
    environment:
      - TZ={{ ntp_timezone }}
    restart: unless-stopped

