services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.1
    container_name: sabnzbd
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
    volumes:
      - /srv/appdata/sabnzbd:/config
      - /mnt/scratch/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ me.uid }}
      - PGID=100
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - /srv/appdata/qbittorrent:/config
      - /mnt/scratch/downloads:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    