---

- name: Set Debian Components on Bookworm and newer
  set_fact:
    debian_components: 'main contrib non-free non-free-firmware'
  when: ansible_distribution_major_version | int >= 12

- name: Set Debian Components on Bullseye and earlier
  set_fact:
    debian_components: 'main contrib non-free'
  when: ansible_distribution_major_version | int <= 11

- name: Update sources.list
  become: true
  template:
    src: sources.list.debian.j2
    dest: /etc/apt/sources.list
  register: debian_apt_config_legacy
  when: apt_source_mode == 'legacy'

- name: Replace sources.list
  become: true
  copy:
    src: debian.sources.list
    dest: /etc/apt/sources.list
  when: apt_source_mode == 'modern'
    
- name: Install debian.sources
  become: true
  template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
  register: ubuntu_apt_config_modern
  when: apt_source_mode == 'modern'


- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: debian_apt_config_legacy.changed or ubuntu_apt_config_modern.changed
