---

# Ubuntu
- name: Configure Ubuntu apt sources
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Debian 
- name: Configure Debian apt sources
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'