services:

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      TZ: {{ ntp_timezone }}
      CRON_MIN: 1,31
    volumes:
      - {{ appdata_path }}/freshrss/data:/var/www/FreshRSS/data
      - {{ appdata_path }}/freshrss/extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped
