---

- name: install required packages
  ansible.builtin.apt:
    name: 
      - moreutils
      - python3-apt
      - nvme-cli
      - jq
    update_cache: yes
    state: present

- name: copy systemd service files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2$', '') }}
    owner: root
    group: root
    mode: 0755
  with_fileglob: "{{ role_path }}/templates/node-exporter-*.j2"
  notify: restart collectors

- name: enable smartmon timer on boot
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: node-exporter-smartmon.timer
    daemon_reload: true

- name: enable nvme metrics timer on boot
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: node-exporter-nvme.timer
    daemon_reload: true

- name: enable apt info timer on boot
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: node-exporter-apt.timer
    daemon_reload: true

  

